### PR TITLE
fix(ui): keep `searchText` in local storage

### PR DESCRIPTION
**Pull request by YLeight**
## Describe your changes
Add `@persist` decorator to ui store's `searchText` field

## Issue ticket number and link
Fix: [#1437](https://github.com/stakwork/sphinx-tribes/issues/1437)

## Type of change

Bug fix (non-breaking change which fixes an issue)

https://jam.dev/c/972b9905-e5c8-41a5-a9fd-1515b9a74e75

### CODE REVIEW

**Comment by YLeight** [comment]
@elraphty @ecurrencyhodler ready for testing and review

**Comment by ecurrencyhodler** [comment]
Video looks good. Sorry one more thing. We have reverted our backend api calls from api.people-test->people.test. So we no longer will require the "api" in front of the call.

Can you push another commit? I think that'll trigger our github actions workflows for testing. Also in the future, you can run the tests locally as well using: `yarn run`.

**Comment by YLeight** [comment]
@ecurrencyhodler ✅

**Comment by ecurrencyhodler** [comment]
Tested and it works great. GJ. Will pay when I get funds.

**Comment by ecurrencyhodler** [comment]
paid

**Pull request merged**
