### PR TITLE
Sort by filter on org

### PR DESCRIPTION
**Pull request by okhot**
## Describe your changes #1326
Implemented Sort by Newest and oldest on the org page

## Issue ticket number and link
https://www.loom.com/share/d11cdfa3cdfc45a7a381589e3c790f21?sid=c74cf43c-a39b-43e1-b100-630bb408a86c

[#1326](https://github.com/stakwork/sphinx-tribes/issues/1326)

- [x] New feature (non-breaking change which adds functionality)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by aliraza556** [comment]
Hi @okhot,
Please add component test in alignment with the recently updated code.
Thank you!

**Comment by aliraza556** [comment]
Hi @okhot,
Your code is currently incomplete and does not fully meet the requirements outlined in the issue. Please double-check your code and the files changed in your previous pull request.
Previous PR Changes:  [PR](https://github.com/stakwork/sphinx-tribes-frontend/pull/48/files#r1479584749)

**Comment by okhot** [comment]
Please can you elaborate on which areas the requirements haven't been met?

**Comment by aliraza556** [comment]
@okhot,
Please check [demo](https://www.loom.com/share/66875c085d7e446cb7d9cda018f1e5ff)

**Comment by ecurrencyhodler** [comment]
Hey @okhot I'm going to close this pr but will pay you out 50% of the bounty. Let's find you a different PR. 

In the future, let's try to rebase before submitting PR's as well as when submitting updates to PR's based on review comments.

**Pull request closed without merging**
