### PR TITLE
Fixed org description not visible for signed out user

### PR DESCRIPTION
**Pull request by chiragDork**
## Describe your changes
Fixed org description not visible for signed out user

Screenshot from 2024-02-22 13-58-48

## Issue ticket number and link
issue: #284 

## Type of change
ui change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by chiragDork** [comment]
Hi @ecurrencyhodler I have fixed the isuse and raised PR

**Comment by elraphty** [comment]
> #284

@chiragDork Please right a test for your change

**Comment by chiragDork** [comment]
Screenshot from 2024-02-22 18-58-06

**Comment by elraphty** [comment]
> @elraphty the test is already covered in the testing file

Post a Bounty button should not be visible if the user is not logged in

```sh
  it('renders the component correctly', async () => {
    render(<OrgHeader {...MockProps} />);
    waitFor(() => {
      expect(screen.findByText(MockProps.organizationData.name ?? '')).toBeInTheDocument();
      expect(screen.findByText(MockProps.organizationData.description ?? '')).toBeInTheDocument();
      expect(screen.getByText('Post a Bounty')).toBeInTheDocument();
      expect(screen.getByText('Status')).toBeInTheDocument();
      expect(screen.getByText('Skill')).toBeInTheDocument();
      expect(screen.getByPlaceholderText('Search')).toBeInTheDocument();
      expect(screen.getByText(/Bounties/i)).toBeInTheDocument();
    });
  });

```

This test doesn't test for that.

**Comment by elraphty** [comment]
> > @elraphty the test is already covered in the testing file
> 
> Post a Bounty button should not be visible if the user is not logged in
> 
> ```shell
>   it('renders the component correctly', async () => {
>     render(<OrgHeader {...MockProps} />);
>     waitFor(() => {
>       expect(screen.findByText(MockProps.organizationData.name ?? '')).toBeInTheDocument();
>       expect(screen.findByText(MockProps.organizationData.description ?? '')).toBeInTheDocument();
>       expect(screen.getByText('Post a Bounty')).toBeInTheDocument();
>       expect(screen.getByText('Status')).toBeInTheDocument();
>       expect(screen.getByText('Skill')).toBeInTheDocument();
>       expect(screen.getByPlaceholderText('Search')).toBeInTheDocument();
>       expect(screen.getByText(/Bounties/i)).toBeInTheDocument();
>     });
>   });
> ```
> 
> This test doesn't test for that.

It covers that the description is always visible, so add the test for the visibility for *Post a Bounty*

**Comment by chiragDork** [comment]
@elraphty I have added the test, Thanks

**Comment by kevkevinpal** [comment]
> @elraphty I have added the test, Thanks

@chiragDork there is still only one file changed in this PR

I would take the same test @elraphty posted and then make `meInfo` empty

The change looks good otherwise!

**Comment by chiragDork** [comment]
Hi @kevkevinpal sorry I missed to add the test file to the commit, I have made the commit again, can you please check and let me know if everything is okay now.
Thanks.

**Comment by elraphty** [comment]
> > @elraphty I have added the test, Thanks
> 
> @chiragDork there is still only one file changed in this PR
> 
> I would take the same test @elraphty posted and then make `meInfo` empty
> 
> The change looks good otherwise!

@chiragDork do this, make the meInfo empty, then write a new test with a populated meInfo, and assert that the Post bounty button is visible.

**Comment by ecurrencyhodler** [comment]
Tested and paid! https://community.sphinx.chat/bounty/1564

**Pull request merged**
