### PR TITLE
Org Filter by Skill

### PR DESCRIPTION
**Pull request by Vayras**
Resubmission of https://github.com/stakwork/sphinx-tribes/pull/1430
issue:https://github.com/stakwork/sphinx-tribes/issues/1315
with this PR I have implemented the skills filter on org Homepage
implementation involves modification of api call getOrganizationBounties and changes in frontend
loom video:https://www.loom.com/share/685883cc25b74f8bae633b85a5d41a00
test have been updated
tested on chrome

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Video looks good. Sorry one more thing. We have reverted our backend api calls from api.people-test->people.test. So we no longer will require the "api" in front of the call.

Can you push another commit? I think that'll trigger our github actions workflows for testing. Also in the future, you can run the tests locally as well using: `yarn run`.

**Comment by ecurrencyhodler** [comment]
Hmmm you have a jest test failing now.

**Comment by Vayras** [comment]
> Hmmm you have a jest test failing now.

@ecurrencyhodler , This is persistent due to the modification of the  `getOrganizationBounties` , we'll need review from @elraphty on this one

**Comment by Vayras** [comment]
@ecurrencyhodler @elraphty fixed issues in this PR, I think we are good to go now , awaiting your review

**Comment by Vayras** [comment]
Screenshot 2024-01-26 at 8 47 28 PM
I have updated the test file but I cannot run the test on my local machine getting this error

**Comment by Vayras** [comment]
I think I will need assistance with this one, I cannot figure out the cause of this test failure

**Comment by Ekep-Obasi** [comment]
@Vayras have pushed 
src/config/ModeDispatcher.tsx
src/config/host.ts 

You should reset the AppMode back to `TRIBES` and return `host` instead of `people-test.sphinx.chat`

**Comment by Vayras** [comment]
> @Vayras, you have pushed src/config/ModeDispatcher.tsx src/config/host.ts
> 
> You should reset the AppMode back to `TRIBES` and return `host` instead of `people-test.sphinx.chat`

@Ekep-Obasi Thank you for your help , I might have pushed these with the other files an oversight at my end

**Comment by elraphty** [comment]
@Vayras fix the alignment of skill and status dropdowns

**Comment by Vayras** [comment]
> @Vayras fix the alignment of skill and status dropdowns 

Sure, will fix this

**Comment by Vayras** [comment]
@elraphty done with the changes

**Pull request merged**
