### PR TITLE
Fix#107: Resize "manage role" window

### LINKED ISSUE #107: Resize "manage role" window
**Describe the bug**
Right now the "manage roles" window for org permissions is not correctly sized.

After adding a user to an org, click on the "gear" icon to manage their roles. 
Screenshot 2024-01-31 at 11 44 20 AM

**Expected behavior**
Follow the design requirements in [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=7776%3A6788&mode=design&t=X6XzrgrSW7pv1Lo4-1).

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot in my PR

### PR DESCRIPTION
**Pull request by VividhPandey003**
## Describe your changes
image

## Issue ticket number and link
Closes #107 
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [ ] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Nice. You have some jest tests failing. Can you take another look?

**Comment by aliraza556** [comment]
Hi @VividhPandey003,
See this PR https://github.com/stakwork/sphinx-tribes-frontend/pull/102/files files changes.

**Comment by VividhPandey003** [comment]
> Hi @VividhPandey003, See this PR https://github.com/stakwork/sphinx-tribes-frontend/pull/102/files files changes.

Hey @aliraza556, I didn't quite get you

**Comment by aliraza556** [comment]
> > Hi @VividhPandey003, See this PR https://github.com/stakwork/sphinx-tribes-frontend/pull/102/files files changes.
> 
> Hey @aliraza556, Oh yeah. That is actually what I meant. So I guess it looks like when you PR gets merged. mine will pass the tests right?

Yes

**Comment by Vayras** [comment]
@VividhPandey003 For the fix for the checks you can make these changes --
1. `${StartDate30.format('DD MMM')} - ${expectedEndDate.format('DD MMM YYYY')}` add this instead of `${StartDate30.format('DD MMM YYYY')} - ${expectedEndDate.format('DD MMM YYYY')}` in SuperAdminHeader.spec.tsx line 68

**Comment by aliraza556** [comment]
@VividhPandey003, you just need to make any changes to your code and commit, and the Jest test will be fixed because this PR (https://github.com/stakwork/sphinx-tribes-frontend/pull/102) has been merged.

**Comment by VividhPandey003** [comment]
> @VividhPandey003 For the fix for the checks you can make these changes --
> 
> 1. `${StartDate30.format('DD MMM')} - ${expectedEndDate.format('DD MMM YYYY')}` add this instead of `${StartDate30.format('DD MMM YYYY')} - ${expectedEndDate.format('DD MMM YYYY')}` in SuperAdminHeader.spec.tsx line 68 
> 
> 

Thanks @Vayras I don't need to make these changes I guess though

**Comment by aliraza556** [comment]
@VividhPandey003 @Vayras 
Now there is no need to make changes in this file `src/pages/superadmin/header/__tests__/SuperAdminHeader.spec.tsx.`

**Comment by VividhPandey003** [comment]
> @VividhPandey003, you just need to make any changes to your code and commit, and the Jest test will be fixed because this PR (https://github.com/stakwork/sphinx-tribes-frontend/pull/102) has been merged.

Ooh, nice. Thanks @aliraza556 for informing

**Comment by ecurrencyhodler** [comment]
LGTM let's get a code review!

**Comment by ecurrencyhodler** [comment]
Tested. LGTM. Paid!

**Pull request merged**
