### PR TITLE
Enabled right click for people page

### PR DESCRIPTION
**Pull request by hritikmunde**
Closes [#1406](https://github.com/stakwork/sphinx-tribes/issues/1406)

Changes Made: Enabled right-click to open a new tab for the People tab

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Can you post the video again? 

Sorry one more thing. We have reverted our backend api calls from api.people-test->people.test. So we no longer will require the "api" in front of the call.

Can you push another commit? I think that'll trigger our github actions workflows for testing. Also in the future, you can run the tests locally as well using: `yarn run`.

**Comment by hritikmunde** [comment]
@ecurrencyhodler , can you approve the run?

**Comment by elraphty** [comment]
@hritikmunde  you have not fixed the design bug yet,Profile list, all the dividers before the connect button are supposed to be on the same line, check community.sphinx.chat to see the difference.

**Comment by elraphty** [comment]
> @elraphty , check now, made some changes

I checked, and there is still a small difference between those with a description and those without, use a max width for each section and maintain the description text ellipsis.

**Comment by hritikmunde** [comment]
@elraphty , will try to fix it although its an existing problem in community,sphinx.chat as well.

**Comment by ecurrencyhodler** [comment]
@elraphty let's not include the design issue into this PR. This PR is just focused on the right click functionality. I can confirm that this is a pre-existing issue.

Since this is a design issue, we may need to address this separately.

**Comment by hritikmunde** [comment]
@ecurrencyhodler @elraphty I'll address this issue in any other PR later on its a small change I guess.

**Comment by ecurrencyhodler** [comment]
LGTM. Tested. Paid!

**Pull request merged**
