### PR TITLE
fix: Disable bounty creation button upon initial click

### LINKED ISSUE #197: Disable bounty creation button upon initial click
**Describe the bug**
Tom S created a bounty and assigned a hunter during the bounty creation flow. This created duplicate bounties. I have tried duplicating but was not successful.

Here are the two bounties: 
https://community.sphinx.chat/bounty/1436
https://community.sphinx.chat/bounty/1437

**To Reproduce**
Create a bounty and assign fog321(in use) to it during bounty creation.

**Expected behavior**
Disable button once it's been clicked and wait for a response before it moves to a failure or success screen.

The success screen is the bounty page being opened and displayed.
Failure screen is being worked on here: https://github.com/stakwork/sphinx-tribes-frontend/pull/5
The button should also be re-enabled if failure state is achieved.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my pr
- [ ] I have created a test that the button becomes disabled on click
- [ ] I have rebased and tested locally before submitting my PR

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

### PR DESCRIPTION
**Pull request by Fog3211**
## Describe your changes
 Disable bounty creation button upon initial click

https://github.com/stakwork/sphinx-tribes-frontend/assets/23151576/0cbcde6a-d960-4b3b-9a6d-51d2e7b55d65

## Issue ticket number and link

closes #197 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x]  I have created a test that the button becomes disabled on click
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Video looks good to me. Good job. Looks like you have a conflicting file. `src/people/main/FocusView.tsx` Can you address that? We recommend resolving conflicts through cli.

**Comment by Fog3211** [comment]
> Video looks good to me. Good job. Looks like you have a conflicting file. `src/people/main/FocusView.tsx` Can you address that? We recommend resolving conflicts through cli.

Try again plz, I have rebased master branch

**Comment by Vayras** [comment]
@Fog3211 good job. Let's test the code locally

**Comment by Vayras** [comment]
works as intended, all checks passed @kevkevinpal, @elraphty I think we can get this one merged

**Comment by ecurrencyhodler** [comment]
Unfortunately I can't test this because there is a breaking change on staging. I created an issue for us to take a look: https://github.com/stakwork/sphinx-tribes-frontend/issues/258

**Comment by ecurrencyhodler** [comment]
Tested and it works. GJ! Paid 200k sats. https://community.sphinx.chat/bounty/1457

**Pull request merged**
