### PR TITLE
Add org name and logo to org home page

### PR DESCRIPTION
**Pull request by NengakDakup**
## Describe your changes
image
Added Company Name, Logo, and Description, implemented fallback Logo Image, and conditional render of Organization Links
## Issue ticket number and link
[#1319](https://github.com/stakwork/sphinx-tribes/issues/1319)
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
@NengakDakup you have quite a few tests failing. Can you take another look?

**Comment by NengakDakup** [comment]
> @NengakDakup you have quite a few tests failing. Can you take another look?

The test i created actually passes when i tested locally, i think the tests failing here are from like other tests...
@kevkevinpal

**Comment by aliraza556** [comment]
Hi @NengakDakup,
No need add new test file this path `src/pages/tickets/org/orgHeader/__tests__/OrgHeaderComponent.spec.tsx`
Please see this path test file already added in code:
`src/people/widgetViews/__tests__/OrgHeader.spec.tsx`

So, remove your test file and move you test code in above path route.

**Comment by aliraza556** [comment]
@NengakDakup,
Also, no need to create a mock data file.
Some fields add [here](https://i.imgur.com/Vm5p2Km.png) according to the your requirement (logo, org_name)

**Comment by aliraza556** [comment]
@NengakDakup see this PR
https://github.com/stakwork/sphinx-tribes-frontend/pull/26

**Comment by NengakDakup** [comment]
@aliraza556 Noted man. Let me make the corrections. What's your username on sphinx so i chat you up if i still have any issues....

**Comment by aliraza556** [comment]
Thanks, @NengakDakup! I appreciate your willingness to make the corrections. My username on Sphinx is `Ali Raza`. Feel free to reach out if you have any more questions or need further assistance.

**Comment by NengakDakup** [comment]
> Hey @NengakDakup looks like you have a conflict with this file: src/pages/tickets/org/orgHeader/index.tsx

Just resolved it

**Comment by kevkevinpal** [comment]
it looks like you have 15 different commits, if you can squash them down into fewer commits that will help us review and rebasing the branch onto master will make the tests pass

**Comment by NengakDakup** [comment]
> it looks like you have 15 different commits, if you can squash them down into fewer commits that will help us review and rebasing the branch onto master will make the tests pass

okay, man. Noted.

**Comment by ecurrencyhodler** [comment]
Hey Nen. This issue was taking too long so raph addressed it in #141. 

I'm going close this issue and pay you out partially for your work.

**Comment by NengakDakup** [comment]
> Hey Nen. This issue was taking too long so raph addressed it in #141.
> 
> I'm going close this issue and pay you out partially for your work.

Okay, man. Great!

**Pull request closed without merging**
