### PR TITLE
Write tests case for wanted

### PR DESCRIPTION
**Pull request by MahtabBukhari**
## Issue ticket number and link
- Issue ticket number #128

## Updated Evidence
image

## Type of change
1. Setting up Jest and its necessary dependencies for testing.
2. mocking some data and functions like `person`, `setupStore`, `user`, `mockUsehistory`, and `mockBounties`.
3. Describing a test suite for the 'wanted' component.
4. Inside this suite, I have tests to ensure that certain functionalities work as expected, like calling a specific function when the component mounts.
5. Testing the rendering of a specific number of bounties created by the user and checking if each bounty is visible on the UI.
6. Another test verifies if clicking on a bounty card redirects to the correct page.
7. I have tests to ensure that the correct message is rendered if no bounties are assigned and if a 'Load More' button is displayed when there are more bounties available.
8. I have tests If no any bounty then show the "No Tickets Yet" text

### CODE REVIEW

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler Kindly review my PR

**Comment by Vayras** [comment]
@MahtabBukhari good job screenshot looks good , let's look at the code once

**Comment by Vayras** [comment]
code looks good, cleared for merging

**Comment by elraphty** [comment]
@MahtabBukhari you didn't write a test for this "Test that clicking on "post a bounty" button takes you through the bounty creation flow."

**Comment by elraphty** [comment]
> @MahtabBukhari you didn't write a test for this "Test that clicking on "post a bounty" button takes you through the bounty creation flow."

@MahtabBukhari can you make a push for this update today, I'm waiting on you so I can merge, I have changed the routes, and merging these changes before yours will break lots of your code.

**Comment by elraphty** [comment]
@MahtabBukhari please fix merge conflicts, thanks.

**Pull request closed without merging**
