### PR TITLE
Improved Select Dropdown component

### LINKED ISSUE #106: Labels Not Hiding on Scroll in Edit Bounty Modal Pop-Up
**Describe the bug**
When editing a bounty, some labels in the edit modal do not hide as they should while scrolling through the pop-up card.

https://www.loom.com/share/0a31f170e5d449e68cba03a778aad028

The problem is the current implementation (elastic UI) of the the dropdown on the site is too abstracted, is not very efficient, and does not behave how a dropdown should actually behave. 

**Expected behavior**
When scrolling in the Edit Bounty Modal, all labels and elements should appropriately respond by moving or hiding, ensuring a smooth and user-friendly interface.

To solve a lot of UI problems as discussed with the core team [@ecurrencyhodler @kevkevinpal @elraphty] we are now slowly moving towards our **own custom components**. This issue will cover dropdowns specifically.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] Include a test that states the dropdown menu persists on scroll if it's open.

### PR DESCRIPTION
**Pull request by Vayras**
With this PR, Previous select dropdown a component from ElasticUI has been changed to our own custom dropdown component. closes #106 

loom video: https://www.loom.com/share/35e4d9c2089d492fb9a06e3ed3a3998e

behaviour changes: on scroll the dropdown will autoclose

### CODE REVIEW

**Comment by Vayras** [comment]
@kevkevinpal can you help me with the Cypress,I cannot figure that out, Thanks

**Comment by kevkevinpal** [comment]
@Vayras I would setup cypress locally to see where the test is failing to help figure out the issue

you can follow this guide here https://github.com/stakwork/sphinx-tribes-frontend/blob/master/docs/setupCypressTest.md

**Comment by Vayras** [comment]
> @Vayras I would setup cypress locally to see where the test is failing to help figure out the issue
> 
> you can follow this guide here https://github.com/stakwork/sphinx-tribes-frontend/blob/master/docs/setupCypressTest.md

I had problems setting it up locally, but will give this one a try once again

**Comment by kevkevinpal** [comment]
> > @Vayras I would setup cypress locally to see where the test is failing to help figure out the issue
> > you can follow this guide here https://github.com/stakwork/sphinx-tribes-frontend/blob/master/docs/setupCypressTest.md
> 
> I had problems setting it up locally, but will give this one a try once again

please send me a message if you're having trouble setting it up

**Comment by tobi-bams** [comment]
@Vayras I fixed the cypress test, please fix the `eslint` check.

The `eslint` check has nothing to do with the cypress test

**Comment by Vayras** [comment]
all checks passed, Thanks to @tobi-bams for fixing cypress for me, @kevkevinpal, @elraphty let me know, when you review this. cc: @ecurrencyhodler

**Comment by elraphty** [comment]
> all checks passed, Thanks to @tobi-bams for fixing cypress for me, @kevkevinpal, @elraphty let me know, when you review this. cc: @ecurrencyhodler

@Vayras nice work.

Screenshoot the select dropdown width seems longer than other inputs or edit, also the dropdown width didn't match that of the input box, also reduce the margin between the dropdown and the input.

**Pull request closed without merging**
