### PR TITLE
fixed Org Scrolling Resubmit

### PR DESCRIPTION
**Pull request by Vayras**
Resubmission of PR on this frontend the issue no:https://github.com/stakwork/sphinx-tribes/issues/1277
Implemented Scrolling on Org page
The scrolling on org work correctly now
video:https://www.loom.com/share/1c2d554581c544829a129f7618588412
Tested on Chrome
Test Files updated

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Video looks good. Sorry one more thing. We have reverted our backend api calls from api.people-test->people.test. So we no longer will require the "api" in front of the call.

Can you push another commit? I think that'll trigger our github actions workflows for testing. Also in the future, you can run the tests locally as well using: `yarn run`.

**Comment by ecurrencyhodler** [comment]
LGTM. Let's get a code review.

**Comment by elraphty** [comment]
Please fix merge conflicts @Vayras

**Comment by Vayras** [comment]
> Please fix merge conflicts @Vayras

@elraphty done

**Comment by elraphty** [comment]
@Vayras fix ESLINT error, uuid is being used before declared in `TicketsModal.tsx`, and the Left and right arrows are not moving to the right bounties, they follow the bounty page order, I will create a new endpoint to create an index of an organization bounty.

**Comment by Vayras** [comment]
@elraphty Okay , will do that

**Comment by ecurrencyhodler** [comment]
Here are the new endpoints: https://github.com/stakwork/sphinx-tribes/compare/1466

**Comment by Vayras** [comment]
@ecurrencyhodler Thanks for the update, I will use this endpoints and update the PR accordingly

**Comment by Vayras** [comment]
@elraphty I'm getting CORS error while calling these new endpoints
Screenshot 2024-01-28 at 5 25 00 PM

this is how I have implemented the api get method in main.ts:

` async GetOrganizationNextBountyById(uuid:string,bountyId:number): Promise<number> {
    try {
      const req = await api.get(`org/next/${uuid}/${bountyId}}`);
      return req;
    } catch (e) {
      console.log('fetch failed getBountyIndexById: ', e);
      return 0;
    }
  }`

**Comment by elraphty** [comment]
> @elraphty I'm getting CORS error while calling these new endpoints Screenshot 2024-01-28 at 5 25 00 PM
> 
> this is how I have implemented the method in main.ts: Screenshot 2024-01-28 at 5 47 27 PM

The right endpoint is `https://people-test.sphinx.chat/gobounties/org/next/{orgId}{bountyId}`

**Comment by ecurrencyhodler** [comment]
@Vayras okay looks like "next" was broken but "previous worked". We are going to do a quick fix for you to test.

**Comment by ecurrencyhodler** [comment]
Okay raph tested again and said the endpoints are working. Can you post the specific endpoint you are calling?

**Comment by Vayras** [comment]
@ecurrencyhodler still getting 404 not found error on both the handlers
Screenshot 2024-01-30 at 11 11 00 PM
Screenshot 2024-01-30 at 11 11 37 PM

**Comment by elraphty** [comment]
@Vayras it's working, your URL is wrongly formatted you have a double slash `//` after `.chat`, try this `https://people-test.sphinx.chat/gobounties/org/next/ck95pe04nncjnaefo08g/1179`.

**Comment by Vayras** [comment]
@elraphty my bad, let me test it again, Thanks

**Comment by Vayras** [comment]
@elraphty @ecurrencyhodler I have got the handlers working fine now, will implemented them and Raise an updated PR soon

**Comment by Vayras** [comment]
Raising a new PR with the latest pull from the master to avoid conflicts

**Pull request closed without merging**
