### PR TITLE
Fix(Bounty-Page): Enhanced Navigation for Direct Access to Bounty Pages

### PR DESCRIPTION
**Pull request by MirzaHanan**
### Problem:
Users experienced inconsistent navigation behavior when closing a bounty page. Specifically, direct access to a bounty page (pasted URL in a new tab) and closing it redirected the user to the Google home page, instead of the more intuitive Sphinx Chat bounties homepage.

### Expected Behavior:
- When a user accesses a bounty page directly and closes it, they should be redirected to the Sphinx Chat bounties homepage (`/bounties`).
- If a user accesses a bounty page from an internal page (like their profile), closing the page should return them to the previous page, not the bounties homepage.

## Issue ticket number and link:
- **Ticket Number:** [ 1362 ]
- **Link:** [ https://github.com/stakwork/sphinx-tribes/issues/1362 ]

### Solution:
To address this issue, we implemented a conditional redirection strategy based on the user's navigation path to the bounty page. This was achieved by utilizing the `useLocation` and `useHistory` hooks from `react-router-dom` and creating a custom logic to determine the user's entry point to the bounty page.

### Changes:
- Utilized `useLocation` and `useHistory` from `react-router-dom` to manage navigation.
- Created `isDirectAccess` function to determine if the page was accessed directly (without a referrer) and contains '/bounty/' in the pathname.
- Developed `handleClose` function to apply conditional redirection: `history.push('/bounties')` for direct access and `history.goBack()` for internal navigation.
- Attached `handleClose` to relevant event handlers (`overlayClick` and `onClick` for the close button) to trigger this navigation logic.

### Evidence:
 Please see the attached video as evidence.
- Demo: [Link ](https://www.loom.com/share/47cb6672c39044a3b190452316110d9f)

### Testing:
Thorough testing was conducted in various scenarios to ensure the functionality works as expected. This includes:
- Direct access to bounty pages and closing them.
- Accessing bounty pages from internal pages and then closing them.
- Testing in different browsers to ensure consistent behavior.

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Thanks mirza!

Video looks good. Sorry one more thing. We have reverted our backend api calls from api.people-test->people.test. So we no longer will require the "api" in front of the call.

Can you push another commit? I think that'll trigger our github actions workflows for testing. Also in the future, you can run the tests locally as well using: `yarn run`.

**Comment by aliraza556** [comment]
Thanks for the update! I'll make the API call adjustments and push a new commit. I'll also remember to run tests locally using 'yarn run' in the future.

**Comment by MirzaHanan** [comment]
Thanks for the update! I'll make the API call adjustments and push a new commit. I'll also remember to run tests locally using 'yarn run' in the future.

**Comment by elraphty** [comment]
Well done @MirzaHanan Merging.

**Comment by MirzaHanan** [comment]
> Well done @MirzaHanan Merging.

Thanks Man!

**Pull request merged**
