### PR TITLE
Fix Edit Profile - Fix padding for input with prepend

### PR DESCRIPTION
**Pull request by ChetanKarwa**
## Describe your changes
I have fixed the padding issue on the profile update page.
This would solve the issue with all inputs. The handling of the left padding is incorrect for input tag.

## Issue ticket number and link
https://github.com/stakwork/sphinx-tribes-frontend/issues/2

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by ChetanKarwa** [comment]
**While Editing**
image


**With Data**
image


**Without Data**
image

**Comment by ecurrencyhodler** [comment]
Great work! All checks passed. Let's get a code review.

**Comment by ecurrencyhodler** [comment]
You have some tests failing.

**Comment by ecurrencyhodler** [comment]
Nice. Tests pass.  Let's get a code review

**Comment by ecurrencyhodler** [comment]
Tested and LGTM. Paid!

**Pull request merged**
