### PR TITLE
PropleList: fix visibility of all languages in filter

### PR DESCRIPTION
**Pull request by ChetanKarwa**
## Issue ticket number and link
https://github.com/stakwork/sphinx-tribes-frontend/issues/40

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by ChetanKarwa** [comment]
image
Here is the New fixed popup

**Comment by ecurrencyhodler** [comment]
This PR should include a test as defined in the acceptance criteria. Can you include that in this PR?

**Comment by ecurrencyhodler** [comment]
you have some tests failing. You can run tests locally using ran before submission.

**Comment by ecurrencyhodler** [comment]
Tested. LGTM

**Comment by ecurrencyhodler** [comment]
paid

**Pull request merged**
