### PR TITLE
Fix: the issue where the page reloads when switching users

### PR DESCRIPTION
**Pull request by Fog3211**
## Describe your changes
Fix the issue of page reload caused by <a> tag href navigation.
Fix the problem where clicking the "connect" button displays the QR code modal and simultaneously navigates to a new page

## Issue ticket number and link

#146 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend
- [x]  I've created a test that asserts the page doesn't reload when switching profiles

https://www.loom.com/share/11fa17f9407a4fdfbb023da651f1055a?sid=a3e6c32f-824d-411d-b923-a88de42f5bc6

### CODE REVIEW

**Comment by aliraza556** [comment]
Hi @Fog3211,
LGTM, Let's proceed with the code review.

**Comment by aliraza556** [comment]
I reviewed the issue and the corresponding code changes. I also conducted local tests to ensure that everything is working as expected without affecting other functionalities.

**Comment by Fog3211** [comment]
> I reviewed the issue and the corresponding code changes. I also conducted local tests to ensure that everything is working as expected without affecting other functionalities.

thanks, ali

**Comment by ecurrencyhodler** [comment]
Tested and paid! GJ!

**Pull request merged**
