### PR TITLE
#163 Added tests for OrganizationDetails

### LINKED ISSUE #163: [Tests][Component] Add tests to src/people/widgetViews/OrganizationDetails.tsx  Add Members Flow
### Context
once a user successfully creates an organization it's details are provide by `OrganizationDetails.tsx`, test the add members flow 

### File to to test
`src/people/widgetViews/OrganizationDetails.tsx`

### File to create
`src/people/widgetViews/OrganizationDetails.spec.tsx`

### Acceptance Criteria
- [ ] Test that add user button shows add user modal
- [ ] Test that typing in a name filters people according to the search term
- [ ] Test that selecting a profile enables "add user" button
- [ ]  Test that add user button adds user as a member to org

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

### PR DESCRIPTION
**Pull request by hritikmunde**
## Issue ticket number and link
Closes #163 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox

### CODE REVIEW

**Comment by hritikmunde** [comment]
E:\Codes\Sphinx_tribe\sphinx-tribes-frontend\node_modules\node-fetch\lib\index.js:1564
      reject(new FetchError("request to ".concat(request.url, " failed, reason: ").concat(err.message), 'system', err));
             ^
FetchError {
  message: 'request to http://localhost:5002/people/search?search=anish&sortBy=owner_alias&limit=4 failed, reason: Nock: No match for request {\n' +
    '  "method": "GET",\n' +
    '  "url": "http://localhost:5002/people/search?search=anish&sortBy=owner_alias&limit=4",\n' +
    '  "headers": {\n' +
    '    "accept": [\n' +
    '      "*/*"\n' +
    '    ],\n' +
    '    "user-agent": [\n' +
    '      "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"\n' +
    '    ],\n' +
    '    "accept-encoding": [\n' +
    '      "gzip,deflate"\n' +
    '    ]\n' +
    '  }\n' +
    '}',
  type: 'system',
  errno: 'ERR_NOCK_NO_MATCH',
  code: 'ERR_NOCK_NO_MATCH'
  
  @Vayras , getting this error running the test in `OrganizationDetails.spec.tsx` and the test is passing when run in a separate file. Any idea about this?

**Comment by hritikmunde** [comment]
@Vayras , maybe we can keep AddUserModal separate as all other tests in the file render OrganizationDetails component

**Comment by Vayras** [comment]
`nock.disableNetConnect();` try commenting this and running the test in same file, if that does not work try to refactor in two seprate files

**Comment by hritikmunde** [comment]
didn't work so separated tests

**Comment by hritikmunde** [comment]
@Vayras , working on my local machine. Here is the screenshot.
image

**Comment by Vayras** [comment]
also noticed that the test for OrganizationDetails.spec seems to have passed and AddUserModal.spec.tsx seems to be failing

**Comment by hritikmunde** [comment]
Yeah for AddUserModal its passing on local.

**Comment by hritikmunde** [comment]
@Vayras ,any update on this? Its passing on my end

**Comment by kevkevinpal** [comment]
going to try re running jest tests git action

**Comment by kevkevinpal** [comment]
> ```
> E:\Codes\Sphinx_tribe\sphinx-tribes-frontend\node_modules\node-fetch\lib\index.js:1564
>       reject(new FetchError("request to ".concat(request.url, " failed, reason: ").concat(err.message), 'system', err));
>              ^
> FetchError {
>   message: 'request to http://localhost:5002/people/search?search=anish&sortBy=owner_alias&limit=4 failed, reason: Nock: No match for request {\n' +
>     '  "method": "GET",\n' +
>     '  "url": "http://localhost:5002/people/search?search=anish&sortBy=owner_alias&limit=4",\n' +
>     '  "headers": {\n' +
>     '    "accept": [\n' +
>     '      "*/*"\n' +
>     '    ],\n' +
>     '    "user-agent": [\n' +
>     '      "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"\n' +
>     '    ],\n' +
>     '    "accept-encoding": [\n' +
>     '      "gzip,deflate"\n' +
>     '    ]\n' +
>     '  }\n' +
>     '}',
>   type: 'system',
>   errno: 'ERR_NOCK_NO_MATCH',
>   code: 'ERR_NOCK_NO_MATCH'
> ```
> 
> @Vayras , getting this error running the test in `OrganizationDetails.spec.tsx` and the test is passing when run in a separate file. Any idea about this?

I think you need to `nock` that request path

**Comment by hritikmunde** [comment]
Okay let me try that

**Comment by hritikmunde** [comment]
@ecurrencyhodler @kevkevinpal @Vayras , I have made changes as suggested the test is passed. Also, I have combined all the tests in one case to avoid repetition as it goes in a chronological order of functionality.

**Pull request merged**
