### PR TITLE
Number of filters selected on the org bounties page for both the status and skill filer  issue : #43

### PR DESCRIPTION
**Pull request by Vayras**
Enabling Number of filters selected on the org bounties page for both the status and skills filter. issue: #43
Loom video:https://www.loom.com/share/dd464c1cdff24b88a7b85c33002fee6e
Tested on Chrome
Jest Test passed locally
Screenshot 2024-02-12 at 2 30 21 PM

### CODE REVIEW

**Comment by aliraza556** [comment]
Hi @Vayras,
Thank you for submitting this PR. However, one aspect does not match the issue's Figma design, as seen [here](https://i.imgur.com/NVEtGaN.png).
Your code's output can be viewed [here](https://i.imgur.com/vTub3Jn.png)

**Comment by Vayras** [comment]
@aliraza556 thanks for pointing that out

**Comment by aliraza556** [comment]
> @aliraza556 thanks for pointing that out

You're welcome! Happy to assist further if needed.

**Comment by Vayras** [comment]
@ecurrencyhodler need your opinion on this one , so the thing is if nothing is selected we have two ways to show the drop down button one is without the space but then it would jump to the left when numbers loads or leaving the ample white space for numbers before hand which looks bit out of place, what would you recommend I go with?

**Comment by Vayras** [comment]
> @Vayras @ecurrencyhodler 
> Please check [here](https://i.imgur.com/QlVFJWV.png)
> Without selecting: [here](https://i.imgur.com/vl4qOG5.png)
> 
> what is your feedback?

Yeah @aliraza556 I think the drop down buttons would jump to accommodate some space for numbers, let's wait for the core team to discuss the ux/ui

**Comment by ecurrencyhodler** [comment]
@Vayras thanks for calling that out. I'll send it to our designer. But another thing I noticed is that I don't see "check marks" when something is selected. Just blue boxes. 

it should look like this:
Screenshot 2024-02-12 at 7 52 36 AM

**Comment by Vayras** [comment]
@ecurrencyhodler okay would add the tick icon to this, Thanks

**Comment by elraphty** [comment]
> @ecurrencyhodler okay would add the tick icon to this, Thanks

@Vayras can you add it today?

**Comment by elraphty** [comment]
> > > @ecurrencyhodler okay would add the tick icon to this, Thanks
> > 
> > 
> > @Vayras can you add it today?
> 
> @elraphty ofcourse, want me to add that to this or a seprate PR cause I'm waiting on the design updates from @ecurrencyhodler for this issue

Add the skills-selected checkmarks to this one, and use the homepage bounties skills-selected as a reference.

**Comment by Vayras** [comment]
@elraphty done

**Comment by Vayras** [comment]
Screenshot 2024-02-13 at 8 14 49 PM

**Comment by ecurrencyhodler** [comment]
Vayras so sorry I got back to you so late. Our designer said they actually want the # inside the arrow. So the arrow pops out to the right when something is selected. Can you make that fix really quick?

**Comment by Vayras** [comment]
@ecurrencyhodler  absolutely, Let me raise a pr for this

**Comment by ecurrencyhodler** [comment]
Paid 200k sats! https://community.sphinx.chat/bounty/1447

**Pull request merged**
