### PR TITLE
Fix/Deliverables (text) the input selected is of Price (Sats)* #132

### PR DESCRIPTION
**Pull request by Abdul-rahman33**
## Fix

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [ ] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend
- [ ] 

Github URL Issue: https://github.com/stakwork/sphinx-tribes-frontend/assets/158618917/376f31a7-0862-4485-8e0f-495e985e663a [https://github.com/stakwork/sphinx-tribes-frontend/issues/130]

Fix:

https://github.com/stakwork/sphinx-tribes-frontend/assets/158618917/bcf445f1-0f95-4169-9ee2-3741cb4f946a

### CODE REVIEW

**Comment by Vayras** [comment]
@Abdul-rahman33 tested on local works as intended lets wait for the workflows to run and review this further

**Comment by Vayras** [comment]
@Abdul-rahman33 run `yarn run prettier` for fix this prettier and we will be good to go for merge

**Comment by Abdul-rahman33** [comment]
> @Abdul-rahman33 run `yarn run prettier` for fixing the prettier check fail and we will be good to go for merge

Done ☑️

**Comment by ecurrencyhodler** [comment]
Hi @Abdul-rahman33 I'm confused by your video. It looks like you are displaying a bug rather than the fix. And the bug doesn't seem to be related to "deliverables" but instead "Github issue url".

**Comment by Abdul-rahman33** [comment]
> Hi @Abdul-rahman33 I'm confused by your video. It looks like you are displaying a bug rather than the fix. And the bug doesn't seem to be related to "deliverables" but instead "Github issue url".

The issue URL Link also has the same problem with the Deliverabels label. I was just showing you that too in the video. I fixed the two issues already though

**Comment by ecurrencyhodler** [comment]
@Abdul-rahman33 okay thanks. In the future you should post a video of the issue you solved and it working properly. 

But thanks for reporting the github issue. Fortunately we have it documented here: https://github.com/stakwork/sphinx-tribes-frontend/issues/130

**Comment by Vayras** [comment]
@Abdul-rahman33 I think if you can you should update the issue description so that when this PR is referenced we can see what was actually fixed, Thanks

**Comment by Abdul-rahman33** [comment]
> @Abdul-rahman33 I think if you can you should update the issue description with proper video so that when this PR is referenced we can see what was actually fixed, Thanks

I'll do that and a second  video for the issues fixed

**Comment by Abdul-rahman33** [comment]
> @Abdul-rahman33 I think if you can you should update the issue description with proper video so that when this PR is referenced we can see what was actually fixed, Thanks

Done !

**Comment by Vayras** [comment]
Great! lets wait for @kevkevinpal to take a final look and get this merged.

**Comment by Abdul-rahman33** [comment]
> tested and it works. paid!

Recieved, thank you

**Pull request merged**
