### PR TITLE
Go Back Fix  issue #87

### PR DESCRIPTION
**Pull request by Vayras**
fixes:#87
issue: history.goBack() use to loop between bounty url and usertickets once a bounty was clicked
cause:history.goBack()
fix:Routing the back button to the page it came from
loom video:https://www.loom.com/share/8bf9e787333a49c5a0f695f3d78cbbd3

### CODE REVIEW

**Comment by Vayras** [comment]
not sure what is causing the jest to fail

**Comment by kevkevinpal** [comment]
I tried rebasing to master to see if that would help with the tests to pass

**Comment by Vayras** [comment]
Thanks @kevkevinpal, looks like jest is still failing, I will try to look into this

**Comment by kevkevinpal** [comment]
> Thanks @kevkevinpal, looks like jest is still failing, I will try to look into this

ya not sure why and its not related to your change at all is what is concerning me

**Comment by Vayras** [comment]
> > Thanks @kevkevinpal, looks like jest is still failing, I will try to look into this
> 
> ya not sure why and its not related to your change at all is what is concerning me

yeah that is bothering me as well, do you think providing a type to the bounty will help?

**Comment by Vayras** [comment]
@kevkevinpal  figure it out, so the cause was a test written before `beforeEach(() =>...);`

**Comment by elraphty** [comment]
please fix merge conflicts

**Comment by Vayras** [comment]
@elraphty done

**Comment by ecurrencyhodler** [comment]
Tested and paid!

**Pull request merged**
