### PR TITLE
🐞fix#145: Loading Wheel is displayed at the top-left corner 

### LINKED ISSUE #145: Loading Wheel is displayed at the top-left corner
**Describe the bug**

https://github.com/stakwork/sphinx-tribes-frontend/assets/91251535/510ac828-6009-43a1-908e-0f73c6c69d98

**Expected behavior**

Loading wheel should appear in the middle like all other pages

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] I've included a test to say that wheel is centered on the page

### PR DESCRIPTION
**Pull request by VividhPandey003**
## Describe your changes

https://github.com/stakwork/sphinx-tribes-frontend/assets/91251535/d8f2798c-b4c5-47e3-b6fb-09a945d87fd4

## Issue ticket number and link
Closes #145 

## Type of change
css fix
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by aliraza556** [comment]
Hi @VividhPandey003,
Run this command: Yarn run prettier

**Comment by VividhPandey003** [comment]
> Hi @VividhPandey003, Run this command: yarn run prettier

done done

**Comment by aliraza556** [comment]
I examined the problem and the related code modifications. Additionally, I performed local testing to confirm that all is functioning as intended without impacting other features. Please, @kevkevinpal, proceed with the merge confidently.

**Comment by ecurrencyhodler** [comment]
Tested and paid! GJ

**Pull request merged**
