### PR TITLE
resolve open bounties background disappear on hover issue

### PR DESCRIPTION
**Pull request by MahtabBukhari**
## Issue ticket number and link
- Issue ticket number: #60
- [Link](https://github.com/stakwork/sphinx-tribes-frontend/issues/60)

## Evidance 
- Evidance video [Link](https://www.loom.com/share/19f3c423f5ac407c8579099222ce9fa2?sid=cefde0a7-2a64-4225-8f37-7ab1e9957af1)

## Changes
- AssignedUnassignedBounties.tsx
1. The pull request includes styling adjustments for the `Bounties` React component.
2. Notable changes involve border styling in the `DescriptionPriceContainer` and adjustments in `UnassignedPersonProfile`.
3. `BountyContainer` now includes `box-sizing: border-box;` and updated styles for `:hover`.
4. `BountyLink` and `BountyContainer` (in the else block) have new `style` attributes setting width and height.

- AssignedUnassignedBounties.spec.tsx
1. The updated code introduces a new test case for the `Bounties` component, focusing on the hover effect of the `DescriptionPriceContainer`.
2. The `onPanelClick` function in `bountyProps` is now created using `jest.fn()` for better mock functionality.
3. Event simulation with `fireEvent.mouseEnter` is employed to mimic a mouse enter event on the `DescriptionPriceContainer`.
4. The test verifies that the container has the expected style (`border: 2px solid rgba(0,130,255,0.2)`) after the mouse enter event.
5. The test case enhances coverage by specifically checking the hover effect on the designated container in the `Bounties` component.

### CODE REVIEW

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler, is there a problem with the online test running? It's strange that I haven't made any changes to this test component, and it's also not related to the current one, but I encountered the issue here.
image

but it is running on locally on my pc 
image

**Comment by ecurrencyhodler** [comment]
Hmm I'm not sure. I'll have our team take a look at it.

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler kindly review my PR.

**Comment by ecurrencyhodler** [comment]
All checks pass! Let's get a code review

**Pull request closed without merging**
