### PR TITLE
Apply filtered search based on server api

### PR DESCRIPTION
**Pull request by YLeight**
## Describe your changes

According to commits history, this PR is

- Clarifying types interface of `Person` component
- Synchronizing local state of `SearchInputText` component, with `ui`'s store `searchText` observable field
- Fixing resetting of search result after use click out of the search input text field
- Removing unnecessary logic of keeping `searchText` in browser local storage
- Resetting `ui`'s store `searchText` field when switching between pages
- Adding synced logic of fetching people data according to search string and selected filter via server api request

## Issue ticket number and link

#1 
#137 
[#1409](https://github.com/stakwork/sphinx-tribes/issues/1409)
[#1437](https://github.com/stakwork/sphinx-tribes/issues/1437)

## Type of change

Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)

https://jam.dev/c/ccfb8324-2e05-430a-91f7-91941aa6c6fb

### CODE REVIEW

**Comment by YLeight** [comment]
Notes: `people/` api uses 'OR' logic in search

This PR based on [this one](https://github.com/stakwork/sphinx-tribes-frontend/pull/7)
This PR is focuesd on filtration search based on server api call

@ecurrencyhodler @kevkevinpal @elraphty FYI

**Comment by elraphty** [comment]
Great Work @YLeight, A little issue when I go to the people tab and search, then return to the people homepage it still persists the search without the search text in the homepage search input
https://www.loom.com/share/24122679c04b48d5a147aa2559e23d67

**Comment by YLeight** [comment]
Suggest more accurate solution (in my oppinion)

This PR is:
- Cleaning `ui`'s `searchText` field on exact clicking on tabs in header
- Keeping `ui`'s `searchText` while switching from people page to person and vise versa

P.S. In this case, clicking `People` tab will open people page with clean search filed. And clicking `Back` button on `Person` page, will open `People` page with used search text, keeping `Back` button semantics

https://jam.dev/c/8a385d24-21ed-4817-81ce-18aa5e7225ef

**Comment by YLeight** [comment]
@elraphty @kevkevinpal @ecurrencyhodler ready for testing and review

**Comment by ecurrencyhodler** [comment]
Paid @YLeight 400k sats. Thanks for going above and beyond. https://community.sphinx.chat/bounty/1268

**Comment by ecurrencyhodler** [comment]
And this one for 200k https://community.sphinx.chat/bounty/1456

**Pull request merged**
