### PR TITLE
🐞Fix#34: Assigned Bounties in People page shows only 10 bounties and load more code fix

### LINKED ISSUE #34: Assigned Bounties in People page shows only 10 bounties and loadmore code fix
**Describe the bug**

Assigned Bounties in People page shows only 10 bounties 
image

**To Reproduce**

https://people-test.sphinx.chat/p/0276681167b8beb1e6113b259504ab7f9d84432cb3626b1f81b388154eb924073f/usertickets

**Expected behavior**
It should display first 20 bounties initially with a loadmore button to display the next bounties

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR

### PR DESCRIPTION
**Pull request by VividhPandey003**
## Describe your changes

https://github.com/stakwork/sphinx-tribes-frontend/assets/91251535/3f2c2507-3b2d-4825-b813-2d3688fe765b

## Issue ticket number and link
closes #34 
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Hey @VividhPandey003 you can run the tests locally using yarn instead of submitting it to github to see if the tests pass.

**Comment by VividhPandey003** [comment]
> Hey @VividhPandey003 you can run the tests locally using yarn instead of submitting it to github to see if the tests pass.

Hmmm okay. I totally forgot about that. Thanks. I'll squash these remaining commits then

**Comment by ecurrencyhodler** [comment]
Great job. Let's get a code review!

**Comment by ecurrencyhodler** [comment]
Tested. LGTM. Paid!

**Pull request merged**
