### PR TITLE
Add test case for UserTicketsView

### PR DESCRIPTION
**Pull request by Nightrider0098**
## Describe your changes
Added tests to src/people/widgetViews/UserTicketsView.tsx

## Issue ticket number and link
https://community.sphinx.chat/bounty/1406

## Type of change
Tests

### CODE REVIEW

**Comment by Vayras** [comment]
hey @Nightrider0098 Have you tested this locally to see if jest has passed for the component? if yes can you post a screenshot of the terminal for reference?

**Comment by Vayras** [comment]
@Nightrider0098 I see you have tried to disable linting to avoid type-definitions and eslint related errors, but since we use typescript to define proper types and that is the general style of the codebase, I'm not sure if that should be done 

@kevkevinpal or @elraphty can you take a look if we can allow eslint to be disabled?

**Comment by Vayras** [comment]
@Nightrider0098 also you should add issue number to the pr itself #129

**Comment by Nightrider0098** [comment]
image

**Comment by elraphty** [comment]
@Nightrider0098  fix prettier error by running `yarn run prettier` and push.

**Comment by ecurrencyhodler** [comment]
Paid 200k sats! https://community.sphinx.chat/bounty/1406

**Pull request merged**
