### PR TITLE
Auto populate Org name for post bounty modal

### PR DESCRIPTION
**Pull request by Vayras**
Resubmission of : https://github.com/stakwork/sphinx-tribes/pull/1343
issue :https://github.com/stakwork/sphinx-tribes/issues/1320
Loom video :https://www.loom.com/share/6ef1ba861cd641dfa3d814e4ee66d52b
Tested on Chrome

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Video looks good. Sorry one more thing. We have reverted our backend api calls from api.people-test->people.test. So we no longer will require the "api" in front of the call.

Can you push another commit? I think that'll trigger our github actions workflows for testing. Also in the future, you can run the tests locally as well using: `yarn run`.

**Comment by ecurrencyhodler** [comment]
Looks like you have a conflicting file: src/config/host.ts

**Comment by Vayras** [comment]
> Looks like you have a conflicting file: src/config/host.ts

@ecurrencyhodler  fixed

**Comment by elraphty** [comment]
@Vayras Your code breaks the Organization Drop down, No organization gets listed Linnk to Loom Video
https://www.loom.com/share/1986741048594198a6e1577e2b68a643

And please remove the commented code block.

**Comment by Vayras** [comment]
@elraphty well, There are two approaches to this , the original list of organization does not list  the bounties Platform, it lists 18 total organization  , the code for that is commented for now , I have both the implementations ready at hand , 
here the video showing all the other organization :https://www.loom.com/share/62ef6756679a41c2a690316c6c9e987c

**Comment by Vayras** [comment]
@ecurrencyhodler @elraphty since Bounty platform was not available , I used this approach to populate it , We can apply whatever works best in this case , let me know your review

**Comment by elraphty** [comment]
> @elraphty well, There are two approaches to this , the original list of organization does not list the bounties Platform, it lists 18 total organization , the code for that is commented for now , I have both the implementations ready at hand , here the video showing all the other organization :https://www.loom.com/share/62ef6756679a41c2a690316c6c9e987c

I can't see your recording @Vayras it's blurry, But I believe the best solution is reducing the Input abstraction and manipulating the dropdown in that post-bounty modal component.

**Comment by Vayras** [comment]
@elraphty @ecurrencyhodler I'm closing this PR and Resubmitting it proper functionality

**Pull request closed without merging**
