### PR TITLE
Add tests to frontend/app/src/pages/tickets/TicketModalPage.tsx View

### PR DESCRIPTION
**Pull request by NengakDakup**
Add tests to frontend/app/src/pages/tickets/TicketModalPage.tsx View Bounty For Signed in Hunter

## Describe your changes
Added specified tests
## Issue ticket number and link
[#229](https://github.com/stakwork/sphinx-tribes-frontend/issues/229)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [ ] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by aliraza556** [comment]
Hi @NengakDakup,
Have you tested this locally to confirm whether Jest has passed for the component? If so, could you please provide a screenshot of the terminal output for reference?

**Comment by aliraza556** [comment]
Hi @NengakDakup,
Please run the command `yarn run prettier` in the terminal.

**Comment by aliraza556** [comment]
Hi @NengakDakup,
Fantastic work on the test suite! It's thorough, well-organized, and highlights your strong testing skills. You've excelled in ensuring comprehensive coverage and code quality. Great job!

**Comment by aliraza556** [comment]
Hi @NengakDakup,
https://www.loom.com/share/a2bdbd536ced415681d652184bd3c913

**Comment by aliraza556** [comment]
Hi @NengakDakup,
Again push the changes.

**Comment by elraphty** [comment]
@NengakDakup You did not test for this 
 "Test that on clicking on "I can help", a Discuss with Bounty Provider pop up should appear including a QR code, button to copy pub key, and connect with sphinx button."

**Comment by elraphty** [comment]
> > @NengakDakup You did not test for this "Test that on clicking on "I can help", a Discuss with Bounty Provider pop up should appear including a QR code, button to copy pub key, and connect with sphinx button."
> 
> I was told by @ecurrencyhodler not to test that yet as there is an issue blocking it [#253](https://github.com/stakwork/sphinx-tribes-frontend/issues/253)

Okay

**Pull request merged**
