### PR TITLE
Clear assignee after saving edit if hunter has been unassigned

### PR DESCRIPTION
**Pull request by AbdulWahab3181**
## Describe your changes

https://github.com/stakwork/sphinx-tribes-frontend/assets/41957704/c9832729-eec0-4fe2-8862-88788524e2a8

## Issue ticket number and link

Closes https://github.com/stakwork/sphinx-tribes-frontend/issues/30

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
you have some jest tests failing. Can you take a look?

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler could you please approve workflows?

**Comment by ecurrencyhodler** [comment]
LGTM. Let's get a code review.

**Comment by ecurrencyhodler** [comment]
Actually @AbdulWahab3181 looks like this doesn't include a test. Can you add a test to check hunter has been cleared when they are unassigned?

**Comment by AbdulWahab3181** [comment]
> Actually @AbdulWahab3181 looks like this doesn't include a test. Can you add a test to check hunter has been cleared when they are unassigned?

The actual problem is that the bounty data is not updated when they are unassigned. This results in the assignee value persisting, causing reassignment when we click on the edit and save buttons. Now, I'm unsure which part of the unit test I should be focusing on.

**Comment by ecurrencyhodler** [comment]
Okay let's do this test:

When a bounty gets unassigned, test that there is a post request to unassign in the backend.

**Comment by elraphty** [comment]
Fix merge conflicts @AbdulWahab3181

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler I wanted to inform you that I have to go out of the city and will be back by Tuesday. I will create and provide unit tests on Tuesday. You can merge the pull request if you want. I will create another one for the unit tests. I hope that works for you.

**Comment by ecurrencyhodler** [comment]
Okay. Let's circle back next Tuesday. By then we should be in a good spot with our pr's.

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler I have created [this pull request](https://github.com/stakwork/sphinx-tribes-frontend/pull/223) to prevent squashing commits, as the current PR is too old and has a lot of changes. It's challenging to resolve multiple conflicts across multiple files without knowledge of others' work. Please review and merge [this pull request](https://github.com/stakwork/sphinx-tribes-frontend/pull/223), it also includes unit tests. I am going to close the current one.

**Pull request closed without merging**
