### PR TITLE
Re-aligned Edit bounty Model

### PR DESCRIPTION
**Pull request by bilalshaikh292**
I have styled the components in edit bounty model except for Assign People (i.e last part of form) and coding language dropdown as styling them make also edits the PostBountyModel.

This issue solves #111 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have provided a recording of changes

### CODE REVIEW

**Comment by bilalshaikh292** [comment]
https://github.com/stakwork/sphinx-tribes-frontend/assets/110531971/d6b6b8fe-36dd-4b45-81bb-9681c916b5bf

**Comment by Vayras** [comment]
@bilalshaikh292 video looks good going to test this on local now, great job so far

**Comment by Vayras** [comment]
@bilalshaikh292 works as intended, let's wait for workflows to run if all checks are passed @kevkevinpal or @elraphty can get this one merged

**Comment by bilalshaikh292** [comment]
ok @Vayras

**Review by kevkevinpal — APPROVED** [review]
lgtm

**Comment by kevkevinpal** [comment]
rebased and ran prettier on [e81cbee](https://github.com/stakwork/sphinx-tribes-frontend/pull/175/commits/e81cbeef12669913236db6c2018f1a0ff46d2507)

Will merge after ci passes

**Comment by ecurrencyhodler** [comment]
Video LGTM. GJ. Let's merge. All checks passed.

**Comment by ecurrencyhodler** [comment]
@bilalshaikh292 I tested on staging and for some reason the align bounty got mutated. Can you fix that? 
Screenshot 2024-02-07 at 2 49 25 PM

**Comment by bilalshaikh292** [comment]
yes @ecurrencyhodler i have seen that should I create another PR or edit this one

**Comment by ecurrencyhodler** [comment]
Create a separate pr please!

**Comment by bilalshaikh292** [comment]
heyy @ecurrencyhodler I have created a PR #175 please have a look.

**Comment by ecurrencyhodler** [comment]
@bilalshaikh292  I'm sorry. There is one more nit. These boxes should be the same width. Can you fix that? I'll create a 25k bounty for you.
Screenshot 2024-02-09 at 10 15 49 AM

**Comment by bilalshaikh292** [comment]
heyy @ecurrencyhodler  I have Already seen that when i was working with the Edit bounty model. like the assign developer sections it also have fixed length and changing that makes changes in Post Bounty model.that is why I kept it as it was . for now I am having some test . I will definatley give it a try once  my test's are Over.

**Comment by ecurrencyhodler** [comment]
Hmm okay. Thanks for reporting that.

**Pull request merged**
