### PR TITLE
Update color of tags to be visible

### PR DESCRIPTION
**Pull request by Fog3211**
## Describe your changes
Update the tag color of Elastic search Language

image
image

## Issue ticket number and link
#116 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by Fog3211** [comment]
The reason for the Jest failure is that the `src/pages/tickets/__tests__/TicketModalPage.spec.tsx` file has failed, and it seems unrelated to the changes I made for this particular session.

**Comment by Vayras** [comment]
@Fog3211 there is a test  written before `beforeEach(()=>...`  block copy the block above all of the tests
Screenshot 2024-02-02 at 10 03 29 AM

**Comment by Vayras** [comment]
I have fixed this in my PR, if that gets merged before you do not need to make any changes

**Comment by ecurrencyhodler** [comment]
Looks like you have a jest test failing. Can you take another look?

**Comment by elraphty** [comment]
@Fog3211 tests are failing

**Comment by Vayras** [comment]
@Fog3211 Rebase to master and the test will pass.

**Comment by ecurrencyhodler** [comment]
Tested and paid!

**Pull request merged**
