### PR TITLE
feat(TicketEditor): Implement Real-Time Ticket Editing with WebSocket Integration

### PR DESCRIPTION
**Pull request by aliraza556**
## Evidence:

https://www.loom.com/share/fd9f8cc0356e482d92d73d4284bf8c28

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [ ] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by aliraza556** [comment]
Hi @humansinstitute, Please review this PR.

**Comment by MahtabBukhari** [comment]
@humansinstitute please review the PR

**Review by tobi-bams — APPROVED** [review]

**Review by tobi-bams — CHANGES_REQUESTED** [review]
Please Fix Prettier

**Comment by MahtabBukhari** [comment]
> Please Fix Prettier

@tobi-bams prettier is failing on all new coming PRs that is not related to this PR

**Comment by tobi-bams** [comment]
@MahtabBukhari I just merged a fix, please can you resolve merge conflict and push again

**Comment by aliraza556** [comment]
@tobi-bams Thanks Man!

**Pull request merged**
