### PR TITLE
Implemented status filter for super admin page

### PR DESCRIPTION
**Pull request by AbdulWahab3181**
## Describe your changes

https://github.com/stakwork/sphinx-tribes-frontend/assets/41957704/80758827-7d64-4a97-aa7f-f3ab40bb39b5

## Issue ticket number and link

Closes https://github.com/stakwork/sphinx-tribes-frontend/issues/187

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler Could you please review this PR.

**Comment by ecurrencyhodler** [comment]
Eslint and prettier test failed.

**Comment by ecurrencyhodler** [comment]
Prettier is still struggling :(

**Comment by AbdulWahab3181** [comment]
> Prettier is still struggling :(

I am not sure why it's causing a problem. It's working fine locally. Could you please rerun the failed job?

image

**Comment by Ekep-Obasi** [comment]
Hi @AbdulWahab3181 
Run > 'yarn run lint'
Please make sure that you don't have more than 69 warnings.

I guess it should show you the exact warnings in the file that is  failing src/pages/superadmin/constants.ts

> 'yarn run lint:fix' should fix the error 

The pre-commit hook runs 'yarn run lint' for you. if you have less than or equal to 69 warnings then you are good to go

**Comment by AbdulWahab3181** [comment]
> Hi @AbdulWahab3181 Run
> 
> > 'yarn run lint'
> > Please make sure that you don't have more than 69 warnings.
> 
> I guess it should show you the exact warnings in the file that is failing src/pages/superadmin/constants.ts
> 
> > 'yarn run lint:fix'
> > should fix the error
> 
> The pre-commit hook runs 'yarn run lint' for you when you are committing. if you have less than or equal to 69 warnings then you are good to go

 I've executed `yarn run lint`, and it reported less than 69 warnings. And there is no warnings in the file that is failing src/pages/superadmin/constants.ts.

image

**Comment by elraphty** [comment]
@AbdulWahab3181 fix prettier by running `yarn run pretter`

**Comment by AbdulWahab3181** [comment]
> @AbdulWahab3181 fix prettier by running `yarn run pretter`

@elraphty Nothing happens when I run `yarn run prettier`, as you can see in the attached video.

**Comment by ecurrencyhodler** [comment]
Check pass! Let's get a code review.

**Comment by Vayras** [comment]
@AbdulWahab3181 same for this one rebase to master and the failing test will be fixed

**Comment by Vayras** [comment]
@AbdulWahab3181 all checks have passed. I will test the code locally now

**Comment by Vayras** [comment]
@AbdulWahab3181 Tested on local this works as intended

**Comment by Vayras** [comment]
@ecurrencyhodler This can be merged once @kevkevinpal approves this and @AbdulWahab3181 can maybe squash their commits for this

**Comment by AbdulWahab3181** [comment]
> @ecurrencyhodler This can be merged once @kevkevinpal approves this and @AbdulWahab3181 can maybe squash their commits for this

@kevkevinpal @Vayras I have created this PR https://github.com/stakwork/sphinx-tribes-frontend/pull/196 to prevent squashing commits, as the current PR is too old and has a lot of changes. It's really difficult to resolve multiple conflicts on multiple files without knowledge of others' work. Please review and merge this PR https://github.com/stakwork/sphinx-tribes-frontend/pull/196 and close the current one

**Pull request closed without merging**
