### PR TITLE
fix: fixed prettier error

### PR DESCRIPTION
**Pull request by tobi-bams**
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [ ] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by aliraza556** [comment]
Hi @tobi-bams, which command is used to fix it?

**Comment by tobi-bams** [comment]
> Hi @tobi-bams, which command is used to fix it?

@aliraza556 the command is: `yarn run prettier`

**Comment by aliraza556** [comment]
> > Hi @tobi-bams, which command is used to fix it?
> 
> @aliraza556 the command is: `yarn run prettier`

I have also used but not effect I don't know why please review it https://github.com/stakwork/sphinx-tribes-frontend/pull/723

**Comment by aliraza556** [comment]
Please see here:

image

**Comment by aliraza556** [comment]
> > Hi @tobi-bams, which command is used to fix it?
> 
> @aliraza556 the command is: `yarn run prettier`

@tobi-bams I have also used but not effect I don't know why please review it https://github.com/stakwork/sphinx-tribes-frontend/pull/723

**Pull request merged**
