### PR TITLE
added cypress test to view bounty modal

### LINKED ISSUE #377: [Test][cypress] View bounty modal
### Context
Currently, we have a cypress command to [create a bounty](https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108) but we want to assert that we can view the bounty modal after creating it

So what we want to do is use create a bounty and then after open the first bounty on the page to view the modal. We want to assert that a few things in the modal appear

- Bounty owner
- Title
- Description
- Acceptance criteria
- Assignee
- sat amount
- estimated time
- copy link button
- share to twitter button
- mark as paid button
- pay bounty button

### File to create
`sphinx-tribes-frontend/cypress/e2e/4_openBountyModal.cy.ts`
there will be modifications to `sphinx-tribes-frontend/cypress/support/commands.ts`

### Acceptance Criteria

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that in the bounty modal the bounty owner appears

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that in the bounty modal the bounty title appears

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that in the bounty modal the bounty description appears

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that in the bounty modal the bounty acceptance criteria appears

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that in the bounty modal the bounty assignee appears

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that in the bounty modal the bounty sat amount appears

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that in the bounty modal the bounty copy link button appears

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that in the bounty modal the bounty estimate time appears

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that in the bounty modal the bounty share to twitter appears

> Given a user is signed in
> When we create a bounty and click on the bounty tile
> Then the test asserts that in the bounty modal the bounty mark as paid button appears

Modal shown below
image
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

### References
Example cypress test
`https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/e2e/0_create_bounty.cy.ts`

### PR DESCRIPTION
**Pull request by okhot**
closes #377

## Checklist before requesting a review
- [X] I have performed a self-review of my code

### CODE REVIEW

**Comment by elraphty** [comment]
@okhot the cypress tests are failing, please take a look.

**Comment by elraphty** [comment]
@okhot I may have to reassign this issue to someone else if you don't round it up today.

**Comment by Vayras** [comment]
@elraphty can I get this one?

**Comment by chiragDork** [comment]
Hi @elraphty can I help on this.

**Comment by saithsab877** [comment]
Hi @okhot,
Please change the file name from `4_openBountyModal.cy.ts` because my issue file name is `14_edit_profile_details.cy.ts`

**Pull request closed without merging**
