### PR TITLE
Fixed org scrolling

### PR DESCRIPTION
**Pull request by Vayras**
Resubmission of PR on this frontend the issue no:https://github.com/stakwork/sphinx-tribes/issues/1277
Implemented Scrolling on Org page
The scrolling on org work correctly now
Loom video:https://www.loom.com/share/6e5a5e64ec7447ec8aa9a619375c7e4a
Tested on Chrome
Test Files updated

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Nice job! all checks passed. Let's get a code review.

**Comment by ecurrencyhodler** [comment]
Hey @Vayras I tested on staging but it looks like the order is still off. In the video below, the 2nd bounty that should appear next appears 4th. Is that an issue with the backend?

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/b8567f48-86b9-4d82-800c-d1db146a81ef

**Comment by Vayras** [comment]
yeah @ecurrencyhodler now the order completely depends on the backend

**Comment by ecurrencyhodler** [comment]
@elraphty you're going to need to take another look at this. But I'll pay you out for your bounty vayras. thanks.

**Pull request merged**
