### PR TITLE
Add tests to frontend/app/src/pages/tickets/TicketModalPage.tsx For Paid State

### PR DESCRIPTION
**Pull request by wright-eric**
## Describe your changes
Add tests to frontend/app/src/pages/tickets/TicketModalPage.tsx For Paid State
## Issue ticket number and link
#122 

## Type of change
- [x] Unit tests

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by aliraza556** [comment]
Hi @wright-eric,
Could you please confirm whether you've carried out testing locally to ensure the component passes the Jest tests? If so, could you kindly share a screenshot of the terminal output as proof?

**Comment by wright-eric** [comment]
@ecurrencyhodler  ready for review

**Comment by wright-eric** [comment]
> Hi @wright-eric, Could you please confirm whether you've carried out testing locally to ensure the component passes the Jest tests? If so, could you kindly share a screenshot of the terminal output as proof?

check the github actions for jest tests.

**Comment by aliraza556** [comment]
Hi @wright-eric,
Please add this unit test last point.  `Test that I can delete a paid bounty after being marked as unpaid`

**Comment by wright-eric** [comment]
> Hi @wright-eric, Please add the last point to this unit test. `Test that I can delete a paid bounty after being marked as unpaid` https://www.loom.com/share/fe0ee564386b4939813389bb2aa98b2a

I have added the test that the you can delete a bounty only when its unpaid and also added that that you can mark the bounty as unpaid when its paid. 

I guess it makes sense to add tests for a singular units not as a whole. And anyways to implement would require the mock store implementation to be changed. Please help me as i am not so sure how to do that

**Comment by ecurrencyhodler** [comment]
@wright-eric we can save that for the E2E test. This is G2G.

**Comment by ecurrencyhodler** [comment]
@elraphty This is ready for review

**Comment by ecurrencyhodler** [comment]
Paid 200k sats! https://community.sphinx.chat/bounty/1472

**Pull request merged**
