### PR TITLE
New Select Dropdown

### PR DESCRIPTION
**Pull request by Vayras**
## Describe your changes
New Select dropdown with custom component removing elastic ui dependency

## Screenshot
Screenshot 2024-02-27 at 7 51 47 AM

## Issue ticket number and link
issue:#106

## Type of change
UI/UX - frontend change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [x] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by Vayras** [comment]
@elraphty I have opened a new PR, due to accidental removal of my fork

**Comment by Vayras** [comment]
Test failing are from `addUsermodal.tsx`  which I think is unrelated to this PR

**Comment by ecurrencyhodler** [comment]
@Vayras I'm experience strange behavior on the dropdown. 

When I click on a dropdown, the size of the modal changes and I am prompted to scroll.

Also when I scroll to the bottom, the dropdown disappears. Do you think your pr introduced these behaviors?

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/8f00c94e-c1e0-4ba1-a7cd-b11858431e95

**Comment by Vayras** [comment]
Hey, @ecurrencyhodler let me try and reproduces these changes on my end, and I'll update the styles if I can see the same, Thanks

**Comment by Vayras** [comment]
@ecurrencyhodler fixed the problem, will update the dropdown with a new PR

**Comment by ecurrencyhodler** [comment]
Thanks @Vayras I'll pay this bounty out now.

**Pull request merged**
