### PR TITLE
Implementation: Add a "Brief" field to the Feature screen.

### LINKED ISSUE #512: Add Brief field to Feature screen
### Context

There is a new page for Feature. A Feature is part of a Workplace and can be compared to an agile epic.

A workspace will have a list of features.

### Design

Remember to use the components from Elastic UI when ever posible https://eui.elastic.co/

This will be the full feature page
image

Your job for this bounty is to create the 'Feature Brief' field. Here are the specifics.
page: /feature/{feature_uuid}

image

- The field will first display as a label. 
- When showing the label, replace \n with <br/> so that new lines are displayed property.
- When clicking Edit on the side menu, a text area appear with the value of the field.
- There will also be two buttons 
- Cancel -> Go back to the label display, 
- Update -> Call endpoint to update value and show label with updated value

Backend Endpoints:

GET /feature/{uuid}

POST /feature
{
	uuid: '{feature_uuid}',
	brief: 'value inside brief text area'
}

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a test that clicks on edit, changes the text area value, clicks update and refresh the page to find the new value
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

### PR DESCRIPTION
**Pull request by aliraza556**
## Describe your changes
- Add a "Brief" field to the Feature screen.

https://www.loom.com/share/421463b04a844ed4ada73fa5315c51dc

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome
- [x] New feature (non-breaking change which adds functionality)
- [x] I have provided a screenshot of changes in my PR

### CODE REVIEW

**Comment by aliraza556** [comment]
Hi @elraphty, Please review this PR

**Comment by elraphty** [comment]
@aliraza556 The cypress test failed

**Comment by MahtabBukhari** [comment]
@elraphty I think there is an issue with that cypress test

**Comment by MahtabBukhari** [comment]
I also have tried my best pull latest code run at local all tests are passed but when I make PR same cypress is going to be fail

**Comment by elraphty** [comment]
> I also have tried my best pull latest code run at local all tests are passed but when I make PR same cypress is going to be fail [stakwork/sphinx-tribes#1653 (comment)](https://github.com/stakwork/sphinx-tribes/pull/1653#issuecomment-2116996563)
> 
> I am trying to fix it from yesterday but not got success

@MahtabBukhari this is what is falling the feature test



Could you try to check that you have not changed the button, I'm sure this passes @AbdulWahab3181 also made a PR yesterday.

**Comment by elraphty** [comment]
> @elraphty my work is on backend side there is no button

SO sorry, this was meant for @aliraza556

**Comment by aliraza556** [comment]
> Could you try to check that you have not changed the button, I'm sure this passes @AbdulWahab3181 also made a PR yesterday.

Ok, I check it and fix it.

**Comment by AbdulWahab3181** [comment]
@elraphty It's also failing in this backend PR: https://github.com/stakwork/sphinx-tribes/pull/1654.

image

**Comment by MahtabBukhari** [comment]
yeah, that's I am saying this is an issue

**Pull request closed without merging**
