### PR TITLE
Fix/1408 people search on person page

### PR DESCRIPTION
**Pull request by YLeight**
## Describe your changes
Add hook for people searching in PeopleList component

## Issue ticket number and link
[#1408 ](https://github.com/stakwork/sphinx-tribes/issues/1408)

## Type of change

New feature (non-breaking change which adds functionality)

https://jam.dev/c/fec834b3-6001-4e66-ba48-8230fa7358a5

### CODE REVIEW

**Comment by YLeight** [comment]
@elraphty @ecurrencyhodler ready for testing and review

**Comment by ecurrencyhodler** [comment]
Video looks good. Sorry one more thing. We have reverted our backend api calls from api.people-test->people.test. So we no longer will require the "api" in front of the call.

Can you push another commit? I think that'll trigger our github actions workflows for testing. Also in the future, you can run the tests locally as well using: `yarn run`.

**Comment by YLeight** [comment]
@ecurrencyhodler @elraphty kindly reminder

**Comment by YLeight** [comment]
@ecurrencyhodler ✅

**Comment by ecurrencyhodler** [comment]
Tested and it works. GJ! Paid!

**Pull request merged**
