### PR TITLE
Clicking Estimate Session Length (text) doesnt open up dropdown

### PR DESCRIPTION
**Pull request by chiragDork**
## #131 https://community.sphinx.chat/p/02cd45d2ec3a7196fc903619ab74a6237790e241e8de562e264d411556d9f15391/usertickets/1376/0

https://www.loom.com/share/f91ef170e34a48478c679932f5c9f0c2?sid=9c0f12e9-128a-4460-9178-b3615de69c61

### CODE REVIEW

**Comment by Vayras** [comment]
@chiragDork  All Checks passed, great start, let's review the core functionality of the code

**Comment by Vayras** [comment]
@chiragDork While the core functionality is working fine the dropdown seems to be opening when clicking on label, I can see that it does not auto close when I click outside of it, can you fix that?

**Comment by chiragDork** [comment]
@Vayras okay, I will look into it

**Comment by ecurrencyhodler** [comment]
@chiragDork have you taken a look at the bug?

**Comment by chiragDork** [comment]
Hi @ecurrencyhodler just working on the fix, will create a PR soon.

**Comment by chiragDork** [comment]
@ecurrencyhodler @Vayras I have fixed the issue with the drop down
https://www.loom.com/share/f37a076af32340b8975e1469b24e8e9d

**Comment by chiragDork** [comment]
@Vayras @ecurrencyhodler how can I fix the cypress tests, I have not Idea about this, rest I have figured out and updated

**Comment by ecurrencyhodler** [comment]
Hmm let me sync with the team.

**Comment by kevkevinpal** [comment]
rebased to [fe149e5](https://github.com/stakwork/sphinx-tribes-frontend/pull/166/commits/fe149e543456660341bc7726f609048fbec5f5e2)

**Comment by ecurrencyhodler** [comment]
@kevkevinpal still failing :(

**Comment by kevkevinpal** [comment]
it says this

```
`<div class="euiText nextText css-g2xc3e-euiText-m">Next</div>`

is being covered by another element:

`<p style="color: rgb(60, 63, 65); font-size: 14px; padding-left: 0px; margin: 0px; font-family: Barlow; font-weight: 500; line-height: 32px; letter-spacing: 0.01em;">Other</p>`
```

**Comment by kevkevinpal** [comment]
I think this line is breaking
https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L138

if we can add another command to click out of the drop down that would probably fix the test, not sure why it is occurring specifically on this PR

**Comment by kevkevinpal** [comment]
one thing I noticed when trying to fix cypress is that if you open the dropdown menu for `Category` and then try to click on it again it does not close the menu

**Comment by kevkevinpal** [comment]
it seems like this PR is causing issues with the drop down not wanting to close @chiragDork

**Comment by chiragDork** [comment]
@kevkevinpal, @ecurrencyhodler, @Vayras l'll try and fix that , also the current implementation of select dropdown is actually wrong it uses a div as a placeholder so I think changing that might fix it

**Comment by Vayras** [comment]
Cypress test passed @kevkevinpal , @elraphty  this one looks good to be merged

**Comment by kevkevinpal** [comment]
@chiragDork 
can we add a test to this cypress test to insure that we can open the drop down and select a value from the dropdown?

https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108

**Comment by kevkevinpal** [comment]
@chiragDork 
just a minor suggestion for commits, 

when rebasing to master in the cli do the following
```
git fetch -a origin
git rebase origin/master
<fix any merge conflicts>
git rebase --continue
```
this will remove commits like the following [039d6a5](https://github.com/stakwork/sphinx-tribes-frontend/pull/166/commits/039d6a57b58c15ee759b3fe364eef0ecdb6a0127)

I also noticed that you had a few commits which had irrelevant changes such as [a48947e](https://github.com/stakwork/sphinx-tribes-frontend/pull/166/commits/a48947e1a3fcfb3350e8992a272f06eb6174ac5a) and [69cbce9](https://github.com/stakwork/sphinx-tribes-frontend/pull/166/commits/69cbce9e2b36c56a0c3bc7dfcfacab6cebdc8edb)
for those you can squash them by doing the following
```
git reset --soft <commit hash>
git add .
git commit -m "new message"
```

This will lead to a much cleaner commit history

I have manually checked the change after we added a new cypress test we should be good to merge this, nice work @chiragDork

**Comment by chiragDork** [comment]
Thank you @kevkevinpal Is there anything I have to add before This can get merged

**Comment by kevkevinpal** [comment]
> Thank you @kevkevinpal Is there anything I have to add before This can get merged

yes please do the following 

> @chiragDork can we add a test to this cypress test to insure that we can open the drop down and select a value from the dropdown?
> 
> https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108

**Comment by chiragDork** [comment]
> > Thank you @kevkevinpal Is there anything I have to add before This can get merged
> 
> yes please do the following
> 
> > @chiragDork can we add a test to this cypress test to insure that we can open the drop down and select a value from the dropdown?
> > https://github.com/stakwork/sphinx-tribes-frontend/blob/master/cypress/support/commands.ts#L108

Okay will do that

**Comment by chiragDork** [comment]
@ColdMice I'm seeing you name popped up in my commits somehow?

**Comment by ColdMice** [comment]
@chiragDork sorry I forked a wrong branch maybe and added a commit hence my name is popping up on this

**Comment by chiragDork** [comment]
@kevkevinpal can I get a review on this now

**Pull request merged**
