### PR TITLE
Update the github readme for the frontend repo of sphinx-tribes

### LINKED ISSUE #8: Update the github readme for the frontend repo of sphinx-tribes
Create documentation on how to run the front end of the bounties home page in the readme.

### PR DESCRIPTION
**Pull request by VividhPandey003**
## Issue ticket number and link

Closes #8

### CODE REVIEW

**Comment by VividhPandey003** [comment]
> Hmm says you have a conflict in readme.md. 

I'll fix this first thing in the morning. I don't have a system right now. Sorry for the delay...

**Comment by VividhPandey003** [comment]
> Hmm says you have a conflict in readme.md.

Resolved the merge conflicts

**Comment by ecurrencyhodler** [comment]
LGTM! Let's get a code review

**Comment by ecurrencyhodler** [comment]
Good work. Paid!

**Pull request merged**
