### PR TITLE
wrapped the title

### PR DESCRIPTION
**Pull request by gouravmpk**
Closes : Wrap text for bounty titles #226
### Changes : 
Wrapped the Title 
### Video :
[screen-capture (1).webm](https://github.com/stakwork/sphinx-tribes-frontend/assets/20900042/01019cd7-3bc6-4990-994b-37d39502a6b8)

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Video LGTM. Thanks

**Comment by aliraza556** [comment]
Hi @gouravmpk,
Please add a component test in alignment with the recently updated code.
Thank you!

**Comment by aliraza556** [comment]
Also, run the Peritter command `yarn run peritter` .

**Comment by gouravmpk** [comment]
> Hi @gouravmpk, Please add a unit test in alignment with the recently updated code. Thank you!

No need for tests here @aliraza556 please check the changes

**Comment by aliraza556** [comment]
Hi @gouravmpk, @ecurrencyhodler
Please Check demo
https://www.loom.com/share/b3e224b9055d43f69906589127f0a297
I cannot change anything in the code, but the issue has already been fixed.

**Comment by ecurrencyhodler** [comment]
It's cuz I think your title has a space. When there is no space, it looks like this:
Screenshot 2024-02-13 at 4 13 30 PM

**Comment by aliraza556** [comment]
I will try it without spaces and then update you.

**Comment by aliraza556** [comment]
> It's cuz I think your title has a space. When there is no space, it looks like this: Screenshot 2024-02-13 at 4 13 30 PM

Yes, you are right. Without spaces, wrap text for bounty titles, and these code changes will work.

**Comment by aliraza556** [comment]
Hi @gouravmpk
Please fix the Prettier

**Comment by gouravmpk** [comment]
@aliraza556 next time I'm on the system will push the prettier fix .

**Comment by ecurrencyhodler** [comment]
Thanks for the quick turnaround. Paid 200k! https://community.sphinx.chat/bounty/1468

**Pull request merged**
