### PR TITLE
Call bounty statuses in superadmin in the beginning 

### PR DESCRIPTION
**Pull request by vishnu552**
All status type(open, assigned, paid) bounty showing on super admin page. issue #285 
#https://www.loom.com/share/de452d3ce8944c208cc98a86a01dead4?sid=8bfbbde6-d33f-4c5c-9cac-3ed05ce2087a

### CODE REVIEW

**Comment by elraphty** [comment]
@vishnu552 please write a test for this change

**Comment by vishnu552** [comment]
Yes sure, Give me some time.

**Comment by vishnu552** [comment]
@elraphty I have added the assertions, Thanks. Review this whenever you see this

**Review by kevkevinpal — APPROVED** [review]
lgtm

**Pull request merged**
