### PR TITLE
Feat/setup cypress

### PR DESCRIPTION
**Pull request by tobi-bams**
## Describe your changes
Set up Cypress

## Issue ticket number and link
#19 and #20
## Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by tobi-bams** [comment]
Uploading Screen Recording 2024-01-27 at 01.23.11.mov…

@ecurrencyhodler here is a screen recording of the test flow on my local machine

**Comment by ecurrencyhodler** [comment]
Ooo @tobi-bams it looks like the video didn't load fully before you submitted. Can you repost the video?

**Comment by tobi-bams** [comment]
https://github.com/stakwork/sphinx-tribes-frontend/assets/56609046/08071218-ea98-4b89-a6bd-cff7976af84e

@ecurrencyhodler

**Comment by ecurrencyhodler** [comment]
Wow this is so cool that it actually goes through the frontend. It's awesome to see that we were able to get signing in to work!!!

**Comment by ecurrencyhodler** [comment]
Hey tobi looks like you have prettier tests failing. Can you take another look?

**Comment by tobi-bams** [comment]
> Hey tobi looks like you have prettier tests failing. Can you take another look?

Thanks @ecurrencyhodler, I just fixed that.

**Comment by ecurrencyhodler** [comment]
All checks pass. Let's get a code review.

**Review by Evanfeenstra — COMMENTED** [review]
- remove the nodes.json from git
- see about running tests in sequence (like login first, then the next test "on top" of that data
- github action for triggering everything on a PR

**Comment by tobi-bams** [comment]
@elraphty I extended this PR here: [link](https://github.com/stakwork/sphinx-tribes-frontend/pull/75)

**Pull request merged**
