### PR TITLE
Add restrictions to the "Edit Organization" UI #9

### PR DESCRIPTION
**Pull request by vishnu552**
Add restrictions to the "Edit Organization" UI issue(#9)  is fixed. limit of character  is added and when user try to write more limit border and text color changes.
Recording #https://www.loom.com/share/9d6ed1b0da4448afa870862d7503e482?sid=e9930d22-8f88-44ca-9e48-17f2a1a3a52d

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Hi @vishnu552 Great work! There is one missing piece though. The "save" button should turn grey and unclickable if it reaches 21 out of 20 characters or 121 out of 120. Can you submit a PR for that? Then I'll pay the bounty. It should match the functionality of adding a new org.


https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/0a901fd8-6e36-4d1d-ae77-0a8c3aa9b083

**Comment by vishnu552** [comment]
@ecurrencyhodler I think that is not required because user can't type more than 20 characters in input box .if you want then I will make change.

**Comment by ecurrencyhodler** [comment]
Yes plz make the change to make the flows consistent.

**Comment by vishnu552** [comment]
@ecurrencyhodler  yes,sure.

**Pull request merged**
