### PR TITLE
🐞Re- Fix#1365: Allow old bounties to be displayed #1375

### PR DESCRIPTION
**Pull request by VividhPandey003**
Resubmission of PR - https://github.com/stakwork/sphinx-tribes/pull/1375

Closes - [#1365](https://github.com/stakwork/sphinx-tribes/issues/1365)

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Sorry one more thing. We have reverted our backend api calls from api.people-test->people.test. So we no longer will require the "api" in front of the call.

Can you push another commit? I think that'll trigger our github actions workflows for testing. Also in the future, you can run the tests locally as well using: `yarn run`.

**Comment by VividhPandey003** [comment]
Okay. Will do

**Comment by VividhPandey003** [comment]
@elraphty could you please review this once

**Comment by ecurrencyhodler** [comment]
Closing this as evan has addressed the bug as he was tackling a larger issue. But good work. I paid you out partially.

**Pull request closed without merging**
