### PR TITLE
Add tests to src/people/widgetViews/OrganizationDetails.tsx Deposit Button Flow 

### PR DESCRIPTION
**Pull request by okhot**
Screenshot 2024-02-14 at 06 02 32

## Describe your changes #181
Wrote test for Deposit Button Flow

## Type of change

Please delete options that are not relevant.

- [x] Code Test

## Checklist before requesting a review
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by Vayras** [comment]
@okhot can you post a screenshot affirming that the test has passed?

**Comment by okhot** [comment]
@Vayras Done

**Comment by Vayras** [comment]
Let's wait for workflows to run

**Comment by ecurrencyhodler** [comment]
Great job @okhot we are going to have more tests coming up. So feel free to request those.

Paid https://community.sphinx.chat/bounty/1429

**Pull request merged**
