### PR TITLE
Fixed: Bounty Status Consistency Between List and Details Views

### LINKED ISSUE #537: [Bug] Bounty status different in list vs details
### Context
If you Navigate to Profile -> Bounties you will see a list similar to this
image

If you don't have any bounties you can create a new one on https://people-test.sphinx.chat/

If you assign a bounty and then set it to completed, the status on the list will be different from the status in the details.

List
image

Details
image

As you can see on the list it states Assigned and on the details its Completed.

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a test that: Creates a bounty, assigns the bounty and checks that the status on the list is the same as on the details  
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

**********
If a PR is not submitted within two days, we will assign the bounty to someone else
Bounty https://community.sphinx.chat/bounty/1995
**********

Here is an [example cypress test](https://github.com/stakwork/sphinx-tribes-frontend/tree/master/cypress/e2e)

### PR DESCRIPTION
**Pull request by aliraza556**
## Describe your changes
- Fix Bounty status different in list vs details

https://www.loom.com/share/c7b4313a1a864849a0d078c789488787

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] I have provided a screenshot of changes in my PR

### CODE REVIEW

**Comment by aliraza556** [comment]
Hi @elraphty, @fvalentiner.
Please review this PR.

**Comment by elraphty** [comment]
@aliraza556 Please make the status pill color for `Completed` equal, on the Modal it has a gold color, while on the list it has a purple color, also it says `Completed` on the Modal and `Complete` on the list, thanks.

**Comment by aliraza556** [comment]
> @aliraza556 Please make the status pill color for `Completed` equal, on the Modal it has a gold color, while on the list it has a purple color, also it says `Completed` on the Modal and `Complete` on the list, thanks.

@elraphty Ok

**Comment by aliraza556** [comment]
Hi @elraphty, Done
image

**Comment by aliraza556** [comment]
Hi @elraphty, Please review this PR.

**Pull request merged**
