### PR TITLE
[Test][Cypress]: Added Cypress Test For Edit Profile Details

### PR DESCRIPTION
**Pull request by saithsab877**
## Describe your changes
This PR adds the Cypress test for `Edit Profile Details`

Closes: #401

## Issue ticket number and link:
- **Ticket Number:** [ 401 ]
- **Link:** [ https://github.com/stakwork/sphinx-tribes-frontend/issues/401 ]

## Type of change

Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device

### CODE REVIEW

**Comment by saithsab877** [comment]
Hi @elraphty,
Could you please tell me about that issue?

**Comment by elraphty** [comment]
> Hi @elraphty, Could you please tell me about that issue?

I was asking if you were facing any blockers. because you did not respond to my comment.

**Comment by saithsab877** [comment]
> > Hi @elraphty, Could you please tell me about that issue?
> 
> @saithsab877 I was asking if you were facing any blockers. because you did not respond to my comment.

I have texted you through the Sphinx app and issue both please check https://github.com/stakwork/sphinx-tribes-frontend/issues/401#issuecomment-2004111966

**Comment by saithsab877** [comment]
> > Hi @elraphty, Could you please tell me about that issue?
> 
> @saithsab877 I was asking if you were facing any blockers. because you did not respond to my comment.

Which comment are you talking about? As I remember, I have responded to all the comments.

**Comment by saithsab877** [comment]
> > Hi @elraphty, Could you please tell me about that issue?
> 
> @saithsab877 I was asking if you were facing any blockers. because you did not respond to my comment.

Hi @elraphty, Which comment are you talking about? As I remember, I have responded to all the comments.

**Pull request closed without merging**
