### PR TITLE
Test cases for frontend/app/src/pages/tickets/TicketModalPage.tsx

### PR DESCRIPTION
**Pull request by KumarNayan**
## Describe your changes
Test cases covering below scenarios - 
Test that the TicketModalPage is rendered when the URL {host}/bounty/{bountyId} is hit.
 Test that the bounty title, description, estimated hours, sats amount is equal that of the mocked bounty
 Test that when a bounty is assigned, the profile image and user name of hunter should appear on top right.
 Test that If a hunter is not assigned, there should be a clickable button "I can help"

## Issue ticket number and link
closes [#1414](https://github.com/stakwork/sphinx-tribes/issues/1414)

## Checklist before requesting a review
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by KumarNayan** [comment]
@ecurrencyhodler @elraphty

**Comment by ecurrencyhodler** [comment]
Looks like some jest tests failed. Can you take another look?

**Comment by KumarNayan** [comment]
> Looks like some jest tests failed. Can you take another look?

@ecurrencyhodler I have pushed fix for failing tests, can you trigger the workflow?

**Comment by KumarNayan** [comment]
@ecurrencyhodler can i get a review for this ? All checks have passed.

**Comment by ecurrencyhodler** [comment]
Paid!

**Pull request merged**
