### PR TITLE
Admin date fix

### PR DESCRIPTION
**Pull request by chiragDork**
##Admin date fix

## #165 

https://www.loom.com/share/55c272ca898147d7ac466a6e440729a0?sid=814d3034-629e-4545-b782-aaeede440557

### CODE REVIEW

**Comment by Vayras** [comment]
@chiragDork I see that previous commits from your other pr is also addeded to this can you fix that?

**Comment by chiragDork** [comment]
@Vayras Done, I have manually removed the files form this PR for now as reverting the commit will affect my other PR

**Comment by Vayras** [comment]
@chiragDork Tested this locally shows the correct date format, once the workflows starts and all checks have passed we can  get this one merged

**Comment by Vayras** [comment]
All Checks passed, that's great. @kevkevinpal This one looks good to be merged.

**Comment by kevkevinpal** [comment]
rebased and squashed to one commit 6a1d91361200b37a4589c2c1e28a61b5f1637eb0

**Comment by kevkevinpal** [comment]
this looks good to me and nice work with the test @chiragDork next time if you can try squashing the commits to only the relevant ones that would be great but nice work on this change!

Will merge when CI is finished running

**Comment by ecurrencyhodler** [comment]
Tested and it works. Thanks for the quick fix. Paid!

**Pull request merged**
