### PR TITLE
Add Chat Component to Workspace View

### PR DESCRIPTION
**Pull request by Shoaibdev7**
## Closed: #758

https://www.loom.com/share/2d574cc6b86b49aea6fe7047bf6e844d

image

image

image

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [ ] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by Shoaibdev7** [comment]
Hi @humansinstitute, Please review this PR.

**Comment by MuhammadUmer44** [comment]
Hi @humansinstitute, could you please merge this PR? The changes are required to address the issue mentioned here: https://github.com/stakwork/sphinx-tribes-frontend/issues/760.

**Comment by humansinstitute** [comment]
@MuhammadUmer44 - merged

**Comment by humansinstitute** [comment]
[Bug] - After creating a new chat. No new chats are shown in the chat history UI on the Workspace page

**Comment by Shoaibdev7** [comment]
@humansinstitute Please review this demo. Nothing is being retrieved from the backend on this route: `      const response = await fetch(`${TribesURL}/hivechat/history/${workspace_uuid}`, `

https://www.loom.com/share/b4daf8133873474e8bbcabf4d34a316f

**Comment by humansinstitute** [comment]
That route is for chat history.  actual route -> `const response = await fetch(${TribesURL}/hivechat/history/${chatID}` 

We are missing an endpoint here for         `r.Get("/", chatHandler.GetChat)`

This looks like my fault got missed off the initial spec here: https://github.com/stakwork/sphinx-tribes/issues/2154

I'll have to add this in the morning.

**Comment by Shoaibdev7** [comment]
> @Shoaibdev7 That route is for chat history. actual route -> `const response = await fetch(${TribesURL}/hivechat/history/${chatID}`
> 
> We are missing an endpoint here for `r.Get("/", chatHandler.GetChat)`
> 
> This looks like my fault got missed off the initial spec here: [stakwork/sphinx-tribes#2154](https://github.com/stakwork/sphinx-tribes/issues/2154)
> 
> I'll have to add this in the morning.
> 
> Task:
> 
> 1. new route `r.Get("/", chatHandler.GetChat)`
> 2. new db function to getChats for a given workspace UUID in https://github.com/stakwork/sphinx-tribes/blob/master/db/chat.go
> 3. Get the workspace ID and call db.getChats (return all chat details, name updated etc)
> 4. Display List of links to chat ids by last updated
> 5. On click load correct chat view.

@humansinstitute No problem at all! If possible, please feel free to assign the newly created issue to me. I'd be happy to work on it.

**Pull request merged**
