### PR TITLE
style: fixed bot modals

### PR DESCRIPTION
**Pull request by Knight0p6**
### Describe your changes

- [x] fixed modal styles on bot page
- [x] On the Bots Page, the forms are now responsive on both mobile and desktop platforms.
- [x] `My Bots`  now displays properly in the mobile view.

### Evidence 

https://www.loom.com/share/edffa79db4524643977a4ffd07199be6?sid=87eabb13-aa19-4f9a-8aff-0448a2574a9a

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome
- [x] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by Vayras** [comment]
Screenshot 2024-02-07 at 8 44 18 PM
tested on local @Knight0p6 not working the same as shown in video

**Comment by Vayras** [comment]
@Knight0p6 let me test this one again, I will get back to you with an update

**Comment by Vayras** [comment]
@Knight0p6 I think there was a problem with styles not loading correctly on my end its working as intended, great job 
Screenshot 2024-02-07 at 10 25 39 PM

**Comment by Vayras** [comment]
@Knight0p6 once the workflows are passed we can get this one merged

**Comment by kevkevinpal** [comment]
@Vayras can you test to see if the submission of a bot works as intended? after we click save?

**Comment by Vayras** [comment]
> @Vayras can you test to see if the submission of a bot works as intended? after we click save?

Sure, just a minute

**Comment by Vayras** [comment]
@kevkevinpal so the submission works, I get an error as alert bot could not be saved

**Comment by Vayras** [comment]
> @Vayras @kevkevinpal This error also occurs as well on the deployed version community.sphinx.chat.
> 
> Please can you confirm this? @Vayras

Yeah @Knight0p6 I don't think that is an issue related to your ticket

**Comment by ecurrencyhodler** [comment]
Let's just fix the style. We can work on saving it after. Thanks. All checks passed. Video looks good.

**Comment by ecurrencyhodler** [comment]
I think saving the modal might be a backend issue. I'm not sure if this feature is well supported.

**Comment by Vayras** [comment]
I think this one cleared for merging

**Comment by ecurrencyhodler** [comment]
Tested and paid!

**Pull request merged**
