### PR TITLE
Fix#143: Enable ability to edit org if website or github isn't provided 

### LINKED ISSUE #143: Enable ability to edit org if website or github isn't provided
**Describe the bug**
I'm unable to edit and save an org if it doesn't have a website or github.

https://github.com/stakwork/sphinx-tribes-frontend/assets/32662508/3e079710-37f4-4b2b-a7af-66d0d608f110

**Expected behavior**
I should only be restricted from saving an org if the name is empty, org name is too long, or description is too long.

**Desktop (please complete the following information):**
 - Browser:Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] I have created a test stating that the save button is enabled if name has a value and website, github, logo, and description are empty.

### PR DESCRIPTION
**Pull request by VividhPandey003**
## Describe your changes

https://github.com/stakwork/sphinx-tribes-frontend/assets/91251535/fd1b5b2e-31e5-4449-93d4-5b986e8c8fb7

## Issue ticket number and link

Closes #143 

Also tests out [1496](https://github.com/stakwork/sphinx-tribes/pull/1496) by @Vayras 
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by Vayras** [comment]
@VividhPandey003  try making the value equal to the expected value that might fix it, also if you can tell me the scope of the testing I can help you further
` expect(received).toBeUndefined()
    Received: "Updated Description"`.

**Comment by VividhPandey003** [comment]
Oh actually I'm working on it. Thanks for having a look. I'll let you know if I face any issues. 
I actually have some more fixes to make right now😅

**Comment by VividhPandey003** [comment]
> @VividhPandey003 #1496 has been merged!

yes I have made the changes. just passing the tests and i'll change the pr from draft to get reviewed

**Comment by Vayras** [comment]
All checks passed and tested, Clear for merging @kevkevinpal

**Comment by Vayras** [comment]
@VividhPandey003 I think after your recent commit Cypress is failing can you take a look?

**Comment by VividhPandey003** [comment]
hmm that is weird.

**Comment by Vayras** [comment]
@kevkevinpal can you check this Cypress Test fail?

**Comment by kevkevinpal** [comment]
rebased and squashed your commits to one [14b3c15](https://github.com/stakwork/sphinx-tribes-frontend/pull/150/commits/14b3c154cce2a840964ed37e55baa529b9b524fb)

**Comment by VividhPandey003** [comment]
> rebased and squashed your commits to one [14b3c15](https://github.com/stakwork/sphinx-tribes-frontend/pull/150/commits/14b3c154cce2a840964ed37e55baa529b9b524fb)

Thanks @kevkevinpal

**Comment by ecurrencyhodler** [comment]
Tested and it works. Good job! Paid.

**Pull request merged**
