### PR TITLE
Cypress test for admin bounties by custom date range

### PR DESCRIPTION
**Pull request by Vayras**
issue: #486

### CODE REVIEW

**Comment by Vayras** [comment]
@elraphty Jest which is unrelated to this PR is failing

**Comment by MuhammadUmer44** [comment]
HI @Vayras, @elraphty, 
When Vayras is give up then please assign me.

**Comment by Vayras** [comment]
> HI @Vayras, @elraphty, 
> When Vayras is give up then please assign me.

@MuhammadUmer44 Hey! This one's done PR is already raised with Cypress passing as per the issue

**Comment by elraphty** [comment]
> > HI @Vayras, @elraphty,
> > When Vayras is give up then please assign me.
> 
> @MuhammadUmer44 Hey! This one's done PR is already raised with Cypress passing as per the issue

@Vayras can you take a second look, @MuhammadUmer44 worked on a similar task

**Comment by Vayras** [comment]
> > > HI @Vayras, @elraphty,
> > > When Vayras is give up then please assign me.
> > 
> > @MuhammadUmer44 Hey! This one's done PR is already raised with Cypress passing as per the issue
> 
> @Vayras can you take a second look, @MuhammadUmer44 worked on a similar task

As in to reference the jest? Sure will do

**Comment by Vayras** [comment]
@elraphty Thanks, will fix this quick

**Comment by Vayras** [comment]
@elraphty all checks have passed

**Comment by elraphty** [comment]
> @elraphty all checks have passed

@Vayras you did not assert the visibility of the bounties

**Comment by Vayras** [comment]
> > @elraphty all checks have passed
> 
> @Vayras you did not assert the visibility of the bounties 

Let me take a look

**Comment by Vayras** [comment]
@elraphty done with the assertion

**Pull request merged**
