### PR TITLE
feat(#1316): Implemented search bar on org home page

### PR DESCRIPTION
**Pull request by AbdulWahab3181**
## Depends On

https://github.com/stakwork/sphinx-tribes/pull/1460

## Describe your changes

https://github.com/stakwork/sphinx-tribes-frontend/assets/41957704/8f132e1b-91a6-4000-9c7f-8fdbbbfa82ad

## Issue ticket number and link

Closes https://github.com/stakwork/sphinx-tribes-frontend/issues/190

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [x] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

### CODE REVIEW

**Comment by kevkevinpal** [comment]
@AbdulWahab3181 if you can fix the merge conflicts that would be great!

**Comment by AbdulWahab3181** [comment]
> @AbdulWahab3181 if you can fix the merge conflicts that would be great!

Fixed

**Comment by Vayras** [comment]
@AbdulWahab3181 Rebasing to master will fix the test failing

**Comment by kevkevinpal** [comment]
also @AbdulWahab3181  it seems like you have 18 separate commits in this change if you maintain a branch with less commits it will be easier to review and will easier for you to rebase to master

**Comment by Vayras** [comment]
@AbdulWahab3181 Rebase to master to fix the test failing

**Comment by AbdulWahab3181** [comment]
@Vayras It's working as expected, as you can see in the attached video. Please ensure that the code from https://github.com/stakwork/sphinx-tribes/pull/1476 and https://github.com/stakwork/sphinx-tribes/pull/1460 is deployed on the specified environment that you are using.
https://www.loom.com/share/ba99f9a9168a4c5da6b1b24e990654cd

**Comment by Vayras** [comment]
@AbdulWahab3181 let me test this again, I would still like to say that search term including values in bracket might not work for example "searching for plebnet" yielded me nothing.

**Comment by Vayras** [comment]
@AbdulWahab3181 so now the search is working as intented , but If I fail the search and replace the search term and do not press `return on my keyboard` I see infinite loading , can we make it so when the search term is removed we see all the bounties again?
see this attached video for reference
https://www.loom.com/share/04b074e745264b73be064705ab3e0988

**Comment by AbdulWahab3181** [comment]
@Vayras Resolved https://www.loom.com/share/4013334f02b94e23b1c07f38a010ecf1. Could you please try now?

**Comment by Vayras** [comment]
@AbdulWahab3181 Great Job, this works correctly now

**Comment by kevkevinpal** [comment]
closing this PR since there is a newer one to review

**Pull request closed without merging**
