### PR TITLE
Fixed(org-fields): Organization Creation Extra Whitespace

### PR DESCRIPTION
**Pull request by aliraza556**
## Describe your changes
- An org can only be created if there is a text character in the name. In other words, an org name with only spaces shouldn't be created.

## Issue ticket number and link:

- **Ticket Number:** [ 267 ]
- **Link:** [ https://github.com/stakwork/sphinx-tribes-frontend/issues/267 ]

### Evidence:
 - Please see the attached video as evidence.
 https://www.loom.com/share/dfda281deb4e41dd866d3d938db3e04b

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] I have tested on Chrome
- [x] I have added unit tests for both tickets.
- [x] I have provided a recording.

### CODE REVIEW

**Comment by aliraza556** [comment]
Hi @kevkevinpal
I did't change anything in this file  `src/people/widgetViews/__tests__/AddUserModal.spec.tsx`
image

**Comment by aliraza556** [comment]
HI @kevkevinpal,
I think the limit issue!  Jest worker encountered 4 child process exceptions, `exceeding retry limit`.
Please check it.
Locally unit test is pass
image

**Comment by aliraza556** [comment]
Hi @elraphty, @ecurrencyhodler, @kevkevinpal, after this PR is merged, the unit tests are failing in the newly created PRs. Kindly check them.
https://github.com/stakwork/sphinx-tribes-frontend/pull/257/files#diff-d2379ee3c7109fbea9ce7dcc4b95c7da14264dbebbe10cf51aa889b1121c6af6

**Comment by kevkevinpal** [comment]
> Hi @elraphty, @ecurrencyhodler, @kevkevinpal, after this PR is merged, the unit tests are failing in the newly created PRs. Kindly check them. https://github.com/stakwork/sphinx-tribes-frontend/pull/257/files#diff-d2379ee3c7109fbea9ce7dcc4b95c7da14264dbebbe10cf51aa889b1121c6af6

yea I can take a look not sure why its failing since it was passing in that PR, maybe its an issue with the network connectivity of the machine github is using to run the action?

**Comment by kevkevinpal** [comment]
I pushed 830b66d6c1e201e7840b46c7aed33d2a66a6a46f to see if it'd fix the unit tests

**Comment by kevkevinpal** [comment]
woohoo the tests are passing, going to review this PR then merge and rebase the other ones

Thanks @aliraza556 for showing me where the failure was

**Comment by ecurrencyhodler** [comment]
Tested and paid 250k! Increased it 50k for helping to debug the test: https://community.sphinx.chat/bounty/1558

**Pull request merged**
